"use client";

import { useEffect, useMemo, useState } from "react";
import { Icon } from "@/components/terminal/Icon";
import { jsonRequest } from "@/lib/controlClient";
import { formatDateTime } from "@/lib/format";
import type { ControlStatus } from "@/lib/terminalTypes";

type ActivityEvent={id:number;observed_at:string;severity:"info"|"success"|"warning"|"critical";component:string;event_type:string;title:string;detail:string;instrument:string|null;metadata:Record<string,unknown>};

export function ActivityPanel({ status }: { status: ControlStatus }) {
  const[events,setEvents]=useState<ActivityEvent[]>([]);const[error,setError]=useState("");const[severity,setSeverity]=useState("all");const[component,setComponent]=useState("all");const[query,setQuery]=useState("");
  useEffect(()=>{let mounted=true;async function load(){try{const data=await jsonRequest<{events:ActivityEvent[]}>("/api/control/activity?limit=300");if(mounted){setEvents(data.events);setError("");}}catch(e){if(mounted)setError(e instanceof Error?e.message:"Activity stream unavailable");}}void load();const timer=window.setInterval(()=>void load(),5000);return()=>{mounted=false;window.clearInterval(timer);};},[]);
  const synthetic=useMemo<ActivityEvent[]>(()=>{const rows:ActivityEvent[]=[];let id=-1;for(const [name,message] of Object.entries(status.controlPlane.errors)){rows.push({id:id--,observed_at:new Date().toISOString(),severity:"critical",component:name,event_type:"control_error",title:`${name} control-plane error`,detail:message,instrument:null,metadata:{}});}if(status.worker.last_error)rows.push({id:id--,observed_at:status.worker.last_heartbeat??new Date().toISOString(),severity:"critical",component:"oracle",event_type:"worker_error",title:"Oracle worker error",detail:status.worker.last_error,instrument:null,metadata:{}});if(status.paperEngine.last_error)rows.push({id:id--,observed_at:status.paperEngine.updated_at??new Date().toISOString(),severity:"critical",component:"paper-engine",event_type:"runtime_error",title:"Paper engine error",detail:status.paperEngine.last_error,instrument:null,metadata:{}});return rows;},[status]);
  const all=[...synthetic,...events];const components=[...new Set(all.map((e)=>e.component))].sort();const filtered=all.filter((event)=>(severity==="all"||event.severity===severity)&&(component==="all"||event.component===component)&&(!query||`${event.title} ${event.detail} ${event.instrument??""}`.toLowerCase().includes(query.toLowerCase())));
  return <>
    {error&&<div className="error-banner">{error}</div>}
    <section className="terminal-section card"><div className="section-heading compact"><div><p className="eyebrow">Persistent observability</p><h2>Alerts &amp; logs</h2></div><span>{events.length} stored events</span></div><div className="filter-row"><select value={severity} onChange={(e)=>setSeverity(e.target.value)}><option value="all">All severities</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="success">Success</option><option value="info">Info</option></select><select value={component} onChange={(e)=>setComponent(e.target.value)}><option value="all">All components</option>{components.map((name)=><option key={name} value={name}>{name}</option>)}</select><input aria-label="Search activity" placeholder="Search events…" value={query} onChange={(e)=>setQuery(e.target.value)}/></div><div className="activity-list">{filtered.length?filtered.map((event)=><article className={`activity-row ${event.severity}`} key={`${event.id}-${event.observed_at}`}><div className="activity-icon"><Icon name={event.severity==="critical"?"shield":event.event_type.includes("signal")?"activity":"info"}/></div><div className="activity-copy"><div><strong>{event.title}</strong><span>{formatDateTime(event.observed_at)}</span></div><p>{event.detail||event.event_type.replaceAll("_"," ")}</p><small>{event.component}{event.instrument?` · ${event.instrument}`:""}</small></div><span className={`status-badge ${event.severity==="critical"?"bad":event.severity==="warning"?"warn":event.severity==="success"?"good":""}`}>{event.severity}</span></article>):<div className="empty-state compact"><Icon name="activity"/><h3>No matching events</h3><p>Adjust the filters or wait for Oracle/control-plane activity.</p></div>}</div><p className="availability-note">Oracle now persists sanitized command, signal, session, risk and paper-trade events. External notification delivery is still separate from the in-app stream.</p></section>
  </>;
}
