import { EmptyState } from "@/components/terminal/EmptyState";
import { MetricCard } from "@/components/terminal/MetricCard";
import { PerformanceChart } from "@/components/terminal/PerformanceChart";
import { formatCurrency, formatNumber, formatPercent } from "@/lib/format";
import { calculatePaperAnalytics, groupPnlBySymbol } from "@/lib/terminalAnalytics";
import type { ControlStatus } from "@/lib/terminalTypes";

function extraAnalytics(status:ControlStatus){const orderById=new Map(status.paperOrders.map((o)=>[o.id,o]));const completed=status.paperTrades.filter((t)=>t.pnl!=null);const returns=completed.map((t)=>{const o=t.order_id?orderById.get(t.order_id):undefined;const basis=(t.entry_price??o?.entry_price??0)*t.quantity;return basis>0?(t.pnl??0)/basis:null;}).filter((x):x is number=>x!=null);const mean=returns.length?returns.reduce((a,b)=>a+b,0)/returns.length:null;const variance=mean!=null&&returns.length>1?returns.reduce((s,x)=>s+(x-mean)**2,0)/(returns.length-1):null;const sharpe=mean!=null&&variance!=null&&variance>0?mean/Math.sqrt(variance):null;const holds=completed.map((t)=>{const o=t.order_id?orderById.get(t.order_id):undefined;return o?Math.max((Date.parse(t.executed_at)-Date.parse(o.created_at))/1000,0):null;}).filter((x):x is number=>x!=null);const avgHold=holds.length?holds.reduce((a,b)=>a+b,0)/holds.length:null;const wins=completed.filter((t)=>(t.pnl??0)>0);const losses=completed.filter((t)=>(t.pnl??0)<0);const winRate=completed.length?wins.length/completed.length:null;const avgWin=wins.length?wins.reduce((s,t)=>s+(t.pnl??0),0)/wins.length:0;const avgLoss=losses.length?Math.abs(losses.reduce((s,t)=>s+(t.pnl??0),0)/losses.length):0;const expectancy=winRate==null?null:winRate*avgWin-(1-winRate)*avgLoss;const rr=avgLoss>0?avgWin/avgLoss:null;const type=(suffix:string)=>{const rows=completed.filter((t)=>t.trading_symbol.endsWith(suffix));return{trades:rows.length,pnl:rows.reduce((s,t)=>s+(t.pnl??0),0),wins:rows.filter((t)=>(t.pnl??0)>0).length};};return{sharpe,avgHold,expectancy,rr,ce:type("CE"),pe:type("PE")};}
function holdText(seconds:number|null){if(seconds==null)return"Unavailable";if(seconds<60)return`${Math.round(seconds)}s`;return`${(seconds/60).toFixed(1)}m`;}
function symbolDrawdown(trades:ControlStatus["paperTrades"],symbol:string){let equity=0,peak=0,draw=0;for(const t of [...trades].filter((x)=>x.trading_symbol===symbol).sort((a,b)=>Date.parse(a.executed_at)-Date.parse(b.executed_at))){equity+=t.pnl??0;peak=Math.max(peak,equity);draw=Math.max(draw,peak-equity);}return draw;}
export function AnalyticsPanel({status}:{status:ControlStatus}){const analytics=calculatePaperAnalytics(status.paperTrades,status.paperOrders);const bySymbol=groupPnlBySymbol(status.paperTrades);const extra=extraAnalytics(status);return <>
<section className="terminal-metric-grid six"><MetricCard label="Net / total P&L" value={formatCurrency(analytics.totalPnl)} detail={`${analytics.completedTrades} realized paper trades`} tone={(analytics.totalPnl??0)>=0?"positive":"negative"} unavailable={analytics.totalPnl===null}/><MetricCard label="Gross profit" value={formatCurrency(analytics.grossProfit)} tone="positive" unavailable={analytics.grossProfit===null}/><MetricCard label="Gross loss" value={formatCurrency(analytics.grossLoss)} tone="negative" unavailable={analytics.grossLoss===null}/><MetricCard label="Win rate" value={formatPercent(analytics.winRate)} unavailable={analytics.winRate===null}/><MetricCard label="Profit factor" value={analytics.profitFactor?.toFixed(2)} unavailable={analytics.profitFactor===null}/><MetricCard label="Maximum drawdown" value={formatCurrency(analytics.maxDrawdown)} tone="negative" unavailable={analytics.maxDrawdown===null}/><MetricCard label="Expectancy / trade" value={formatCurrency(extra.expectancy)} unavailable={extra.expectancy===null}/><MetricCard label="Avg reward / risk" value={extra.rr!=null?`${extra.rr.toFixed(2)}×`:undefined} unavailable={extra.rr===null}/><MetricCard label="Average hold" value={holdText(extra.avgHold)} unavailable={extra.avgHold===null}/><MetricCard label="Trade-return Sharpe" value={extra.sharpe?.toFixed(2)} unavailable={extra.sharpe===null} detail="Non-annualized paper trade returns"/><MetricCard label="Paper fees" value="₹0.00" detail="No transaction-cost model configured"/><MetricCard label="Paper slippage" value="0.00" detail="Entry LTP simulation policy"/></section>
<section className="dashboard-grid terminal-section"><article className="card span-8"><PerformanceChart trades={status.paperTrades}/></article><article className="card span-4"><div className="section-heading compact"><div><p className="eyebrow">Performance window</p><h2>Realized P&amp;L</h2></div></div><div className="diagnostic-list"><div><span>Today</span><strong>{formatCurrency(analytics.todayPnl)}</strong></div><div><span>This week</span><strong>{formatCurrency(analytics.weekPnl)}</strong></div><div><span>This month</span><strong>{formatCurrency(analytics.monthPnl)}</strong></div><div><span>Largest winner</span><strong className="good">{formatCurrency(analytics.largestWinner)}</strong></div><div><span>Largest loser</span><strong className="bad">{formatCurrency(analytics.largestLoser)}</strong></div></div></article></section>
<section className="dashboard-grid terminal-section"><article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Option side</p><h2>CE vs PE performance</h2></div></div><div className="diagnostic-list"><div><span>Calls · {extra.ce.trades} trades</span><strong className={extra.ce.pnl>=0?"good":"bad"}>{formatCurrency(extra.ce.pnl)} · {extra.ce.trades?formatPercent(extra.ce.wins/extra.ce.trades):"—"}</strong></div><div><span>Puts · {extra.pe.trades} trades</span><strong className={extra.pe.pnl>=0?"good":"bad"}>{formatCurrency(extra.pe.pnl)} · {extra.pe.trades?formatPercent(extra.pe.wins/extra.pe.trades):"—"}</strong></div></div></article><article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Execution model</p><h2>Paper analytics contract</h2></div></div><div className="diagnostic-list"><div><span>Entry fill</span><strong>Selected option LTP</strong></div><div><span>Exit fill</span><strong>Observed option-chain LTP</strong></div><div><span>Slippage</span><strong>0 by simulation policy</strong></div><div><span>Fees / taxes</span><strong>0 until a cost model is configured</strong></div><div><span>Live broker fills</span><strong>Not claimed</strong></div></div></article></section>
<section className="terminal-section card"><div className="section-heading compact"><div><p className="eyebrow">Breakdown</p><h2>Performance by instrument</h2></div><span>Persisted paper trades</span></div>{bySymbol.length===0?<EmptyState icon="analytics" title="No strategy breakdown yet" description="The comparison table will populate from real closed paper trades."/>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Instrument</th><th>Trades</th><th>Win rate</th><th>Net P&amp;L</th><th>Drawdown</th></tr></thead><tbody>{bySymbol.map((row)=><tr key={row.symbol}><td><strong>{row.symbol}</strong></td><td className="numeric">{row.trades}</td><td className="numeric">{formatPercent(row.wins/row.trades)}</td><td className={`numeric ${row.pnl>=0?"good":"bad"}`}>{formatCurrency(row.pnl)}</td><td className="numeric bad">{formatCurrency(symbolDrawdown(status.paperTrades,row.symbol))}</td></tr>)}</tbody></table></div>}<p className="availability-note">Sharpe shown above is a non-annualized statistic across realized paper-trade returns. It is intentionally not presented as a portfolio/time-series Sharpe.</p></section>
</>;}
