import { EmptyState } from "@/components/terminal/EmptyState";
import { MetricCard } from "@/components/terminal/MetricCard";
import { PerformanceChart } from "@/components/terminal/PerformanceChart";
import { formatCurrency, formatPercent } from "@/lib/format";
import { calculatePaperAnalytics, groupPnlBySymbol } from "@/lib/terminalAnalytics";
import type { ControlStatus, PaperOrder, PaperTrade } from "@/lib/terminalTypes";

function extraAnalytics(status:ControlStatus){const orderById=new Map(status.paperOrders.map((o)=>[o.id,o]));const completed=status.paperTrades.filter((t)=>t.pnl!=null);const returns=completed.map((t)=>{const o=t.order_id?orderById.get(t.order_id):undefined;const basis=(t.entry_price??o?.entry_price??0)*t.quantity;return basis>0?(t.pnl??0)/basis:null;}).filter((x):x is number=>x!=null);const mean=returns.length?returns.reduce((a,b)=>a+b,0)/returns.length:null;const variance=mean!=null&&returns.length>1?returns.reduce((s,x)=>s+(x-mean)**2,0)/(returns.length-1):null;const sharpe=mean!=null&&variance!=null&&variance>0?mean/Math.sqrt(variance):null;const holds=completed.map((t)=>{const o=t.order_id?orderById.get(t.order_id):undefined;return o?Math.max((Date.parse(t.executed_at)-Date.parse(o.created_at))/1000,0):null;}).filter((x):x is number=>x!=null);const avgHold=holds.length?holds.reduce((a,b)=>a+b,0)/holds.length:null;const wins=completed.filter((t)=>(t.pnl??0)>0);const losses=completed.filter((t)=>(t.pnl??0)<0);const winRate=completed.length?wins.length/completed.length:null;const avgWin=wins.length?wins.reduce((s,t)=>s+(t.pnl??0),0)/wins.length:0;const avgLoss=losses.length?Math.abs(losses.reduce((s,t)=>s+(t.pnl??0),0)/losses.length):0;const expectancy=winRate==null?null:winRate*avgWin-(1-winRate)*avgLoss;const rr=avgLoss>0?avgWin/avgLoss:null;const type=(suffix:string)=>{const rows=completed.filter((t)=>t.trading_symbol.endsWith(suffix));return{trades:rows.length,pnl:rows.reduce((s,t)=>s+(t.pnl??0),0),wins:rows.filter((t)=>(t.pnl??0)>0).length};};return{sharpe,avgHold,expectancy,rr,ce:type("CE"),pe:type("PE")};}
function holdText(seconds:number|null){if(seconds==null)return"Unavailable";if(seconds<60)return`${Math.round(seconds)}s`;return`${(seconds/60).toFixed(1)}m`;}
function symbolDrawdown(trades:ControlStatus["paperTrades"],symbol:string){let equity=0,peak=0,draw=0;for(const t of [...trades].filter((x)=>x.trading_symbol===symbol).sort((a,b)=>Date.parse(a.executed_at)-Date.parse(b.executed_at))){equity+=t.pnl??0;peak=Math.max(peak,equity);draw=Math.max(draw,peak-equity);}return draw;}

function strategyName(order: PaperOrder | undefined) {
  const event=(order?.signal_event??"").toLowerCase();
  if(event==="breakout")return"S/R Breakout";
  if(event==="reversal")return"S/R Reversal";
  return event?event.replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase()):"Unclassified";
}
function periodStarts(now=new Date()){const today=new Date(now);today.setHours(0,0,0,0);const week=new Date(today);const day=(week.getDay()+6)%7;week.setDate(week.getDate()-day);const month=new Date(now.getFullYear(),now.getMonth(),1);return{today:today.getTime(),week:week.getTime(),month:month.getTime()};}
function pnlSince(rows:PaperTrade[],since:number){return rows.filter((t)=>Date.parse(t.executed_at)>=since).reduce((sum,t)=>sum+(t.pnl??0),0);}
function strategyAnalytics(status:ControlStatus){const byOrder=new Map(status.paperOrders.map((row)=>[row.id,row]));const groups=new Map<string,{strategy:string;mode:string;trades:PaperTrade[]}>();for(const trade of status.paperTrades.filter((row)=>row.pnl!=null)){const order=trade.order_id?byOrder.get(trade.order_id):undefined;const strategy=strategyName(order);const mode=(order?.mode??trade.mode??"paper").toUpperCase();const key=`${mode}:${strategy}`;const group=groups.get(key)??{strategy,mode,trades:[]};group.trades.push(trade);groups.set(key,group);}const starts=periodStarts();return[...groups.values()].map((group)=>{const wins=group.trades.filter((t)=>(t.pnl??0)>0).length;return{...group,today:pnlSince(group.trades,starts.today),week:pnlSince(group.trades,starts.week),month:pnlSince(group.trades,starts.month),total:group.trades.reduce((sum,t)=>sum+(t.pnl??0),0),winRate:group.trades.length?wins/group.trades.length:null};}).sort((a,b)=>b.month-a.month);}

export function AnalyticsPanel({status}:{status:ControlStatus}){const analytics=calculatePaperAnalytics(status.paperTrades,status.paperOrders);const bySymbol=groupPnlBySymbol(status.paperTrades);const extra=extraAnalytics(status);const byStrategy=strategyAnalytics(status);const starts=periodStarts();const realized=status.paperTrades.filter((t)=>t.pnl!=null);const whole={today:pnlSince(realized,starts.today),week:pnlSince(realized,starts.week),month:pnlSince(realized,starts.month),total:realized.reduce((sum,t)=>sum+(t.pnl??0),0)};return <>
<section className="terminal-metric-grid six"><MetricCard label="Whole realized P&L" value={formatCurrency(whole.total)} detail={`${realized.length} realized trades · PAPER + LIVE`} tone={whole.total>=0?"positive":"negative"}/><MetricCard label="Today" value={formatCurrency(whole.today)} tone={whole.today>=0?"positive":"negative"}/><MetricCard label="This week" value={formatCurrency(whole.week)} tone={whole.week>=0?"positive":"negative"}/><MetricCard label="This month" value={formatCurrency(whole.month)} tone={whole.month>=0?"positive":"negative"}/><MetricCard label="Win rate" value={formatPercent(analytics.winRate)} unavailable={analytics.winRate===null}/><MetricCard label="Maximum drawdown" value={formatCurrency(analytics.maxDrawdown)} tone="negative" unavailable={analytics.maxDrawdown===null}/><MetricCard label="Gross profit" value={formatCurrency(analytics.grossProfit)} tone="positive" unavailable={analytics.grossProfit===null}/><MetricCard label="Gross loss" value={formatCurrency(analytics.grossLoss)} tone="negative" unavailable={analytics.grossLoss===null}/><MetricCard label="Profit factor" value={analytics.profitFactor?.toFixed(2)} unavailable={analytics.profitFactor===null}/><MetricCard label="Expectancy / trade" value={formatCurrency(extra.expectancy)} unavailable={extra.expectancy===null}/><MetricCard label="Avg reward / risk" value={extra.rr!=null?`${extra.rr.toFixed(2)}×`:undefined} unavailable={extra.rr===null}/><MetricCard label="Average hold" value={holdText(extra.avgHold)} unavailable={extra.avgHold===null}/><MetricCard label="Trade-return Sharpe" value={extra.sharpe?.toFixed(2)} unavailable={extra.sharpe===null} detail="Non-annualized realized trade returns"/><MetricCard label="Largest winner" value={formatCurrency(analytics.largestWinner)} tone="positive" unavailable={analytics.largestWinner===null}/><MetricCard label="Largest loser" value={formatCurrency(analytics.largestLoser)} tone="negative" unavailable={analytics.largestLoser===null}/></section>
<section className="terminal-section card"><div className="section-heading compact"><div><p className="eyebrow">Strategy attribution</p><h2>P&amp;L by strategy</h2></div><span>Today · Week · Month · Total</span></div>{byStrategy.length===0?<EmptyState icon="analytics" title="No strategy P&L yet" description="Breakout and reversal attribution appears after positions are closed."/>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Strategy</th><th>Mode</th><th>Today</th><th>Week</th><th>Month</th><th>Total</th><th>Trades</th><th>Win rate</th></tr></thead><tbody>{byStrategy.map((row)=><tr key={`${row.mode}-${row.strategy}`}><td><strong>{row.strategy}</strong></td><td><span className={`status-badge ${row.mode==="LIVE"?"bad":"warn"}`}>{row.mode}</span></td><td className={`numeric ${row.today>=0?"good":"bad"}`}>{formatCurrency(row.today)}</td><td className={`numeric ${row.week>=0?"good":"bad"}`}>{formatCurrency(row.week)}</td><td className={`numeric ${row.month>=0?"good":"bad"}`}>{formatCurrency(row.month)}</td><td className={`numeric ${row.total>=0?"good":"bad"}`}>{formatCurrency(row.total)}</td><td className="numeric">{row.trades.length}</td><td className="numeric">{row.winRate==null?"—":formatPercent(row.winRate)}</td></tr>)}</tbody><tfoot><tr><td><strong>WHOLE PORTFOLIO</strong></td><td>ALL</td><td className={`numeric ${whole.today>=0?"good":"bad"}`}>{formatCurrency(whole.today)}</td><td className={`numeric ${whole.week>=0?"good":"bad"}`}>{formatCurrency(whole.week)}</td><td className={`numeric ${whole.month>=0?"good":"bad"}`}>{formatCurrency(whole.month)}</td><td className={`numeric ${whole.total>=0?"good":"bad"}`}>{formatCurrency(whole.total)}</td><td className="numeric">{realized.length}</td><td className="numeric">{analytics.winRate==null?"—":formatPercent(analytics.winRate)}</td></tr></tfoot></table></div>}<p className="availability-note">Breakout and reversal are attributed from the persisted entry signal. PAPER and LIVE are kept as separate rows so simulated and broker P&amp;L are never silently mixed.</p></section>
<section className="dashboard-grid terminal-section"><article className="card span-8"><PerformanceChart trades={status.paperTrades}/></article><article className="card span-4"><div className="section-heading compact"><div><p className="eyebrow">Performance window</p><h2>Realized P&amp;L</h2></div></div><div className="diagnostic-list"><div><span>Today</span><strong>{formatCurrency(whole.today)}</strong></div><div><span>This week</span><strong>{formatCurrency(whole.week)}</strong></div><div><span>This month</span><strong>{formatCurrency(whole.month)}</strong></div><div><span>All loaded history</span><strong>{formatCurrency(whole.total)}</strong></div><div><span>Largest winner</span><strong className="good">{formatCurrency(analytics.largestWinner)}</strong></div><div><span>Largest loser</span><strong className="bad">{formatCurrency(analytics.largestLoser)}</strong></div></div></article></section>
<section className="dashboard-grid terminal-section"><article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Option side</p><h2>CE vs PE performance</h2></div></div><div className="diagnostic-list"><div><span>Calls · {extra.ce.trades} trades</span><strong className={extra.ce.pnl>=0?"good":"bad"}>{formatCurrency(extra.ce.pnl)} · {extra.ce.trades?formatPercent(extra.ce.wins/extra.ce.trades):"—"}</strong></div><div><span>Puts · {extra.pe.trades} trades</span><strong className={extra.pe.pnl>=0?"good":"bad"}>{formatCurrency(extra.pe.pnl)} · {extra.pe.trades?formatPercent(extra.pe.wins/extra.pe.trades):"—"}</strong></div></div></article><article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Execution model</p><h2>Fill accounting</h2></div></div><div className="diagnostic-list"><div><span>Paper entry</span><strong>Selected option LTP</strong></div><div><span>Paper exit</span><strong>Observed option-chain LTP</strong></div><div><span>LIVE entry/exit</span><strong>Reconciled Groww average fill</strong></div><div><span>Paper slippage</span><strong>0 by simulation policy</strong></div><div><span>Fees / taxes</span><strong>0 until cost model is configured</strong></div></div></article></section>
<section className="terminal-section card"><div className="section-heading compact"><div><p className="eyebrow">Breakdown</p><h2>Performance by instrument</h2></div><span>Persisted closed trades</span></div>{bySymbol.length===0?<EmptyState icon="analytics" title="No instrument breakdown yet" description="The comparison table will populate from real closed paper/live trades."/>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Instrument</th><th>Trades</th><th>Win rate</th><th>Net P&amp;L</th><th>Drawdown</th></tr></thead><tbody>{bySymbol.map((row)=><tr key={row.symbol}><td><strong>{row.symbol}</strong></td><td className="numeric">{row.trades}</td><td className="numeric">{formatPercent(row.wins/row.trades)}</td><td className={`numeric ${row.pnl>=0?"good":"bad"}`}>{formatCurrency(row.pnl)}</td><td className="numeric bad">{formatCurrency(symbolDrawdown(status.paperTrades,row.symbol))}</td></tr>)}</tbody></table></div>}<p className="availability-note">The terminal currently loads the latest 500 closed trades; with the configured daily trade cap this comfortably covers day/week/month views. Sharpe remains a non-annualized realized-trade statistic.</p></section>
</>;}
