import { EmptyState } from "@/components/terminal/EmptyState";
import { formatCompact, formatCurrency, formatNumber, formatPercent } from "@/lib/format";
import type { ControlStatus } from "@/lib/terminalTypes";

function signed(value:number|undefined|null,digits=3){if(value==null||!Number.isFinite(value))return"—";return`${value>0?"+":""}${formatNumber(value,digits)}`;}
function pct(value:number|undefined|null){return value==null?"—":formatPercent(value);}

export function LiveStrategyCalculations({status}:{status:ControlStatus}){
  const signal=status.latestSignal?.payload;
  const engine=status.paperEngine;
  const contract=signal?.contract.contract;
  if(!signal)return <section className="terminal-section card"><div className="section-heading compact"><div><p className="eyebrow">Live calculations</p><h2>Strategy calculation snapshot</h2></div></div><EmptyState icon="strategy" title="Waiting for a calculation snapshot" description="All live formula outputs will appear here after the engine evaluates its first valid market snapshot."/></section>;
  return <section className="terminal-section"><div className="section-heading compact"><div><p className="eyebrow">Live calculations</p><h2>Every active strategy input &amp; score</h2></div><span>{new Date(status.latestSignal!.observed_at).toLocaleString("en-IN")}</span></div>
    <section className="terminal-metric-grid six"><div className="metric-card"><span>Setup</span><strong>{signal.event.toUpperCase()}</strong><small>{signal.level.level_name??"No level"}</small></div><div className="metric-card"><span>Direction</span><strong>{signal.direction.toUpperCase()}</strong><small>{signed(signal.combined_direction_score)}</small></div><div className="metric-card"><span>Confidence</span><strong>{pct(signal.confidence)}</strong><small>{signal.risk.allowed?"Risk ALLOW":"Risk BLOCK"}</small></div><div className="metric-card"><span>NIFTY</span><strong>{formatNumber(engine.nifty_ltp)}</strong><small>VWAP {formatNumber(engine.synthetic_vwap)}</small></div><div className="metric-card"><span>Whole-NIFTY 1m volume</span><strong>{formatCompact(engine.whole_nifty_volume_delta)}</strong><small>{formatCurrency(engine.whole_nifty_turnover)} turnover</small></div><div className="metric-card"><span>Data age</span><strong>{engine.data_age_seconds!=null?`${formatNumber(engine.data_age_seconds,1)}s`:"—"}</strong><small>{engine.constituents_fresh??0}/{engine.constituents_total??50} constituents</small></div></section>
    <section className="dashboard-grid">
      <article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Cash / NIFTY-50</p><h3>Participation calculations</h3></div><strong>{signed(signal.cash.score)}</strong></div><div className="diagnostic-list"><div><span>Cash pressure</span><strong>{signed(signal.cash.pressure)}</strong></div><div><span>Breadth</span><strong>{signed(signal.cash.breadth)}</strong></div><div><span>Participation</span><strong>{formatNumber(signal.cash.participation)}</strong></div><div><span>Signed volume acceleration</span><strong>{signed(signal.cash.signed_volume_acceleration)}</strong></div><div><span>Heavyweight score</span><strong>{signed(signal.cash.heavyweight_score)}</strong></div><div><span>Advancers / Decliners</span><strong>{signal.cash.advancers} / {signal.cash.decliners}</strong></div><div><span>Active constituents</span><strong>{signal.cash.active_count??"—"}</strong></div><div><span>Share volume delta</span><strong>{formatCompact(signal.cash.share_volume_delta)}</strong></div><div><span>Turnover delta</span><strong>{formatCurrency(signal.cash.turnover_delta)}</strong></div></div></article>
      <article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">NIFTY futures</p><h3>Confirmation calculations</h3></div><strong>{signed(signal.futures.score)}</strong></div><div className="diagnostic-list"><div><span>Price direction</span><strong>{signed(signal.futures.price_direction)}</strong></div><div><span>Volume activity</span><strong>{formatNumber(signal.futures.volume_activity)}</strong></div><div><span>OI confirmation</span><strong>{signed(signal.futures.oi_confirmation)}</strong></div><div><span>Basis change</span><strong>{signed(signal.futures.basis_change)}</strong></div><div><span>Future LTP</span><strong>{formatNumber(engine.future_ltp)}</strong></div><div><span>Combined direction score</span><strong>{signed(signal.combined_direction_score)}</strong></div></div></article>
      <article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Options positioning</p><h3>Directional confirmation</h3></div><strong>{signal.option_market?.ready?signed(signal.option_market.score):"WARMING"}</strong></div><div className="diagnostic-list"><div><span>Volume imbalance</span><strong>{signed(signal.option_market?.volume_imbalance)}</strong></div><div><span>OI-change imbalance</span><strong>{signed(signal.option_market?.oi_change_imbalance)}</strong></div><div><span>IV skew</span><strong>{signed(signal.option_market?.iv_skew)}</strong></div><div><span>CE / PE Δ volume</span><strong>{formatCompact(signal.option_market?.call_volume_delta)} / {formatCompact(signal.option_market?.put_volume_delta)}</strong></div><div><span>CE / PE Δ OI</span><strong>{formatCompact(signal.option_market?.call_oi_delta)} / {formatCompact(signal.option_market?.put_oi_delta)}</strong></div><div><span>Contracts used</span><strong>{signal.option_market?.contracts_used??0}</strong></div></div></article>
      <article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">VWAP + level event</p><h3>Breakout / reversal calculations</h3></div><strong>{signal.level.event.toUpperCase()}</strong></div><div className="diagnostic-list"><div><span>VWAP distance</span><strong>{signed(signal.vwap?.distance_bps,1)} bps</strong></div><div><span>VWAP score</span><strong>{signed(signal.vwap?.score)}</strong></div><div><span>Level distance</span><strong>{signed(signal.level.distance_bps,1)} bps</strong></div><div><span>Penetration</span><strong>{formatNumber(signal.level.penetration)}</strong></div><div><span>Rejection</span><strong>{formatNumber(signal.level.rejection)}</strong></div><div><span>Persistence</span><strong>{formatNumber(signal.level.persistence)}</strong></div><div><span>Breakout score</span><strong>{formatNumber(signal.level.breakout_score)}</strong></div><div><span>Reversal score</span><strong>{formatNumber(signal.level.reversal_score)}</strong></div><div><span>Chosen event score</span><strong>{formatNumber(signal.level.event_score)}</strong></div></div></article>
      <article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Selected contract</p><h3>{contract?.trading_symbol??"No contract selected"}</h3></div><strong>{contract?`${contract.option_type} ${formatNumber(contract.strike,0)}`:"—"}</strong></div><div className="diagnostic-list"><div><span>Option score</span><strong>{formatNumber(signal.contract.score)}</strong></div><div><span>LTP</span><strong>{formatNumber(contract?.ltp)}</strong></div><div><span>Delta</span><strong>{formatNumber(contract?.greeks?.delta)}</strong></div><div><span>Gamma</span><strong>{formatNumber(contract?.greeks?.gamma,4)}</strong></div><div><span>Theta</span><strong>{formatNumber(contract?.greeks?.theta)}</strong></div><div><span>IV</span><strong>{contract?.greeks?.iv!=null?`${formatNumber(contract.greeks.iv)}%`:"—"}</strong></div><div><span>OI / Volume</span><strong>{formatCompact(contract?.open_interest)} / {formatCompact(contract?.volume)}</strong></div><div><span>Bid / Ask</span><strong>{formatNumber(contract?.bid_price)} / {formatNumber(contract?.ask_price)}</strong></div></div><p className="availability-note">{signal.contract.reason}</p></article>
      <article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Risk verdict</p><h3>{signal.risk.allowed?"ENTRY ALLOWED":"ENTRY BLOCKED"}</h3></div><strong>{signal.risk.quantity} qty</strong></div><div className="diagnostic-list"><div><span>Quantity</span><strong>{signal.risk.quantity}</strong></div><div><span>Max premium risk</span><strong>{formatCurrency(signal.risk.max_premium_risk)}</strong></div><div><span>Reason</span><strong>{signal.risk.reason}</strong></div><div><span>Execution mode</span><strong>{(status.executionControl?.mode??engine.mode??"paper").toUpperCase()}</strong></div><div><span>Kill switch</span><strong>{engine.kill_switch?"ACTIVE":"CLEAR"}</strong></div></div><p className="availability-note">{signal.reasons.join(" · ")}</p></article>
    </section>
  </section>;
}
