"use client";

import { useEffect, useMemo, useState } from "react";
import { EmptyState } from "@/components/terminal/EmptyState";
import { MetricCard } from "@/components/terminal/MetricCard";
import NiftyVolumeChart, { type NiftyVolumePoint } from "@/components/NiftyVolumeChart";
import { jsonRequest } from "@/lib/controlClient";
import { formatCompact, formatCurrency, formatNumber, formatPercent } from "@/lib/format";
import type { ControlStatus } from "@/lib/terminalTypes";

type Constituent={observed_at:string;symbol:string;sector:string|null;price:number;previous_price:number;move_pct:number;cumulative_volume:number;volume_delta:number;volume_rate:number;relative_volume:number;index_weight:number;is_heavyweight:boolean};
type OptionRow={observed_at:string;expiry:string;underlying_ltp:number|null;strike:number;option_type:"CE"|"PE";trading_symbol:string;ltp:number;open_interest:number;volume:number;delta:number|null;gamma:number|null;theta:number|null;vega:number|null;rho:number|null;iv:number|null;bid_price:number|null;ask_price:number|null};
type MarketPayload={constituents:Constituent[];optionChain:OptionRow[];summary:{constituentObservedAt:string|null;optionObservedAt:string|null;pcrOi:number|null;pcrVolume:number|null;callIv:number|null;putIv:number|null}};
type ResearchPayload={niftyVolumeSeries:NiftyVolumePoint[]};

export function MarketOverviewPanel({ status }: { status: ControlStatus }) {
  const paper=status.paperEngine; const[detail,setDetail]=useState<MarketPayload|null>(null);const[volume,setVolume]=useState<NiftyVolumePoint[]>([]);const[error,setError]=useState("");
  useEffect(()=>{let mounted=true;async function load(){try{const[market,research]=await Promise.all([jsonRequest<MarketPayload>("/api/control/market"),jsonRequest<ResearchPayload>("/api/control/research")]);if(mounted){setDetail(market);setVolume(research.niftyVolumeSeries??[]);setError("");}}catch(e){if(mounted)setError(e instanceof Error?e.message:"Market detail unavailable");}}void load();const timer=window.setInterval(()=>void load(),15000);return()=>{mounted=false;window.clearInterval(timer);};},[]);
  const sectors=useMemo(()=>{const map=new Map<string,{move:number;count:number;volume:number}>();for(const row of detail?.constituents??[]){const key=row.sector??"Other";const item=map.get(key)??{move:0,count:0,volume:0};item.move+=row.move_pct;item.count+=1;item.volume+=row.volume_delta;map.set(key,item);}return[...map.entries()].map(([sector,item])=>({sector,move:item.count?item.move/item.count:0,volume:item.volume,count:item.count})).sort((a,b)=>b.move-a.move);},[detail]);
  const basis=paper.nifty_ltp&&paper.future_ltp?paper.future_ltp-paper.nifty_ltp:null;
  return <>
    {error&&<div className="error-banner">{error}</div>}
    <section className="terminal-metric-grid four"><MetricCard label="NIFTY" value={formatNumber(paper.nifty_ltp)} detail={paper.synthetic_vwap?`VWAP ${formatNumber(paper.synthetic_vwap)}`:"Synthetic VWAP warming"} icon="chart"/><MetricCard label="Nearest future" value={formatNumber(paper.future_ltp)} detail={paper.future_symbol??"Unavailable"}/><MetricCard label="Futures basis" value={basis==null?"Unavailable":`${basis>=0?"+":""}${formatNumber(basis)} pts`} unavailable={basis==null}/><MetricCard label="Fresh constituents" value={`${paper.constituents_fresh??0}/${paper.constituents_total??50}`} detail={`Weighting: ${paper.weighting??"unknown"}`} /></section>
    <section className="terminal-section card"><div className="section-heading compact"><div><p className="eyebrow">Whole NIFTY participation</p><h2>1-minute NIFTY-50 volume</h2></div><span>TradingView-style minute bars · constituent-derived</span></div><NiftyVolumeChart points={volume}/></section>
    <section className="dashboard-grid terminal-section"><article className="card span-7"><div className="section-heading compact"><div><p className="eyebrow">NIFTY-50 tape</p><h2>Constituent movement &amp; participation</h2></div><span>{detail?.summary.constituentObservedAt?new Date(detail.summary.constituentObservedAt).toLocaleTimeString("en-IN"):"Waiting"}</span></div>{detail?.constituents.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Symbol</th><th>Sector</th><th>Price</th><th>Move</th><th>Δ volume</th><th>RVOL</th><th>Role</th></tr></thead><tbody>{detail.constituents.map((row)=><tr key={row.symbol}><td><strong>{row.symbol}</strong></td><td>{row.sector??"Other"}</td><td className="numeric">{formatNumber(row.price)}</td><td className={`numeric ${row.move_pct>=0?"good":"bad"}`}>{row.move_pct>=0?"+":""}{formatNumber(row.move_pct)}%</td><td className="numeric">{formatCompact(row.volume_delta)}</td><td className="numeric">{formatNumber(row.relative_volume,2)}×</td><td>{row.is_heavyweight?<span className="status-badge good">Heavyweight</span>:"Constituent"}</td></tr>)}</tbody></table></div>:<EmptyState icon="chart" title="Constituent telemetry is warming" description="Rows are persisted after each valid Oracle quote scan."/>}</article><article className="card span-5"><div className="section-heading compact"><div><p className="eyebrow">Sector breadth</p><h2>Heatmap summary</h2></div></div>{sectors.length?<div className="diagnostic-list">{sectors.map((row)=><div key={row.sector}><span>{row.sector} · {row.count}</span><strong className={row.move>=0?"good":"bad"}>{row.move>=0?"+":""}{formatNumber(row.move)}% · {formatCompact(row.volume)}</strong></div>)}</div>:<p className="muted">Sector telemetry will appear after the first detailed scan.</p>}<div className="diagnostic-list"><div><span>Whole-NIFTY Δ volume</span><strong>{formatCompact(paper.whole_nifty_volume_delta)}</strong></div><div><span>Turnover</span><strong>{formatCurrency(paper.whole_nifty_turnover)}</strong></div><div><span>Breadth</span><strong>{formatPercent(paper.breadth)}</strong></div><div><span>Participation</span><strong>{formatPercent(paper.participation)}</strong></div><div><span>Heavyweight score</span><strong>{formatNumber(paper.heavyweight_score)}</strong></div></div></article></section>
    <section className="terminal-section card"><div className="section-heading compact"><div><p className="eyebrow">Near-ATM chain</p><h2>NIFTY options</h2></div><div className="section-meta"><span>PCR OI {formatNumber(detail?.summary.pcrOi)}</span><span>PCR Vol {formatNumber(detail?.summary.pcrVolume)}</span><span>CE IV {detail?.summary.callIv!=null?`${formatNumber(detail.summary.callIv)}%`:"—"}</span><span>PE IV {detail?.summary.putIv!=null?`${formatNumber(detail.summary.putIv)}%`:"—"}</span></div></div>{detail?.optionChain.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Strike</th><th>Type</th><th>LTP</th><th>OI</th><th>Volume</th><th>IV</th><th>Delta</th><th>Theta</th><th>Spread</th></tr></thead><tbody>{detail.optionChain.map((row)=><tr key={`${row.strike}-${row.option_type}`}><td className="numeric"><strong>{formatNumber(row.strike,0)}</strong></td><td><span className={`status-badge ${row.option_type==="CE"?"good":"warn"}`}>{row.option_type}</span></td><td className="numeric">{formatNumber(row.ltp)}</td><td className="numeric">{formatCompact(row.open_interest)}</td><td className="numeric">{formatCompact(row.volume)}</td><td className="numeric">{row.iv!=null?`${formatNumber(row.iv)}%`:"—"}</td><td className="numeric">{formatNumber(row.delta)}</td><td className="numeric">{formatNumber(row.theta)}</td><td className="numeric">{row.bid_price!=null&&row.ask_price!=null?formatNumber(row.ask_price-row.bid_price):"—"}</td></tr>)}</tbody></table></div>:<EmptyState icon="chart" title="Option-chain telemetry is warming" description="Oracle persists the nearest 11 strikes after each option-chain refresh."/>}<p className="availability-note">This view is the persisted near-ATM chain used by the trading engine. PCR/IV are descriptive research telemetry; they are not treated as buyer/seller identity.</p></section>
  </>;
}
