"use client";

import { useEffect, useState } from "react";
import { Icon } from "@/components/terminal/Icon";
import { jsonRequest } from "@/lib/controlClient";
import { formatCurrency, formatNumber } from "@/lib/format";
import type { BacktestRequest, BacktestResult, ControlStatus } from "@/lib/terminalTypes";

type ReplayRun = { id:string; status:string; request:BacktestRequest; result:BacktestResult|null; error:string|null; created_at:string; completed_at?:string|null };

export function ReplayPanel({ status }: { status: ControlStatus }) {
  const today = new Date().toLocaleDateString("en-CA");
  const [form, setForm] = useState<BacktestRequest>({ instrument:"NIFTY", date:today, startTime:"09:25", endTime:"15:15", strategyId:"current", strategyVersion:"DB current", startingCapital:status.paperEngine.account_equity ?? 2_000_000, confirmations:["volume","futures","oi","options"] });
  const [run, setRun] = useState<ReplayRun|null>(null);
  const [busy,setBusy]=useState(false); const [notice,setNotice]=useState("");
  useEffect(() => {
    if (!run || !["queued","running"].includes(run.status)) return;
    const timer = window.setInterval(async () => { try { const data=await jsonRequest<{run:ReplayRun|null}>(`/api/control/replay?id=${run.id}`); if (data.run) setRun(data.run); } catch {} }, 1500);
    return () => window.clearInterval(timer);
  }, [run?.id,run?.status]);
  function toggle(name:"volume"|"futures"|"oi"|"options") { setForm((current)=>({...current,confirmations:current.confirmations.includes(name)?current.confirmations.filter((item)=>item!==name):[...current.confirmations,name]})); }
  async function submit() { setBusy(true);setNotice("");try{const data=await jsonRequest<{run:ReplayRun}>("/api/control/replay",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setRun(data.run);setNotice("Replay queued on Oracle using stored market snapshots.");}catch(e){setNotice(e instanceof Error?e.message:"Replay request failed");}finally{setBusy(false);} }
  const result=run?.result;
  return <>
    {notice&&<div className="notice" role="status"><Icon name="replay"/>{notice}</div>}
    <section className="dashboard-grid terminal-section"><article className="card span-5"><div className="section-heading compact"><div><p className="eyebrow">Deterministic research</p><h2>Backtest / Replay</h2></div><span>Stored snapshots only</span></div><div className="form-grid compact"><label className="field"><span>Instrument</span><select value={form.instrument} disabled><option>NIFTY</option></select></label><label className="field"><span>Date</span><input type="date" value={form.date} onChange={(e)=>setForm({...form,date:e.target.value})}/></label><label className="field"><span>Start IST</span><input type="time" value={form.startTime} onChange={(e)=>setForm({...form,startTime:e.target.value})}/></label><label className="field"><span>End IST</span><input type="time" value={form.endTime} onChange={(e)=>setForm({...form,endTime:e.target.value})}/></label><label className="field"><span>Starting capital</span><input type="number" min="1" value={form.startingCapital} onChange={(e)=>setForm({...form,startingCapital:Number(e.target.value)})}/></label><label className="field"><span>Strategy version</span><input value={form.strategyVersion} onChange={(e)=>setForm({...form,strategyVersion:e.target.value})}/></label></div><div className="filter-row"><span>Confirmations</span>{(["volume","futures","oi","options"] as const).map((name)=><button key={name} type="button" className={`filter-chip ${form.confirmations.includes(name)?"active":""}`} onClick={()=>toggle(name)}>{name.toUpperCase()}</button>)}</div><button className="primary full-width" type="button" disabled={busy||!status.worker.online||!form.date} onClick={()=>void submit()}>{busy?<Icon name="refresh" className="spin"/>:<Icon name="replay"/>}Run historical replay</button><p className="availability-note">Replay uses only snapshots captured by this system. It re-runs signal classification/risk deterministically and intentionally does not invent historical broker fills or P&amp;L.</p></article>
      <article className="card span-7"><div className="section-heading compact"><div><p className="eyebrow">Replay result</p><h2>{run?`Run ${run.id.slice(0,8)}`:"No replay selected"}</h2></div>{run&&<span className={`status-badge ${run.status==="completed"?"good":run.status==="failed"?"bad":"warn"}`}>{run.status}</span>}</div>{run?.error&&<div className="error-banner">{run.error}</div>}<div className="terminal-metric-grid three"><div className="metric-card"><span>Frames</span><strong>{result?.frames??"—"}</strong><small>Stored snapshots evaluated</small></div><div className="metric-card"><span>Breakouts</span><strong>{result?.breakouts??"—"}</strong><small>Reclassified events</small></div><div className="metric-card"><span>Reversals</span><strong>{result?.reversals??"—"}</strong><small>Reclassified events</small></div><div className="metric-card"><span>Uncertain</span><strong>{result?.uncertain??"—"}</strong><small>No-trade classification</small></div><div className="metric-card"><span>Risk approved</span><strong>{result?.riskApproved??"—"}</strong><small>Signals passing risk</small></div><div className="metric-card"><span>P&amp;L</span><strong>Not simulated</strong><small>No invented fills</small></div></div>{result?.message&&<p className="availability-note">{result.message}</p>}</article></section>
    <section className="terminal-section card"><div className="section-heading compact"><div><p className="eyebrow">Coverage</p><h2>What replay can prove</h2></div></div><div className="diagnostic-list"><div><span>Stored market state</span><strong>Constituents + futures + options + VWAP</strong></div><div><span>Strategy thresholds</span><strong>Captured with each snapshot</strong></div><div><span>Level state</span><strong>Captured with each snapshot</strong></div><div><span>Historical broker fill</span><strong>Not fabricated</strong></div><div><span>Current starting capital</span><strong>{formatCurrency(form.startingCapital)}</strong></div><div><span>Live stored observations</span><strong>{formatNumber(status.recentSignals.length,0)} recent signals + snapshot history</strong></div></div></section>
  </>;
}
