"use client";

import { useState } from "react";
import { BackendUnavailable } from "@/components/terminal/EmptyState";
import { Icon } from "@/components/terminal/Icon";
import type { BacktestRequest } from "@/lib/terminalTypes";

export function ReplayPanel() {
  const [request, setRequest] = useState<BacktestRequest>({ instrument: "NIFTY", date: "", startTime: "09:15", endTime: "15:15", strategyId: "level-event", strategyVersion: "current", startingCapital: 100000, confirmations: ["volume", "futures", "oi", "options"] });
  function toggle(value: BacktestRequest["confirmations"][number]) {
    setRequest((current) => ({ ...current, confirmations: current.confirmations.includes(value) ? current.confirmations.filter((item) => item !== value) : [...current.confirmations, value] }));
  }
  return <>
    <section className="dashboard-grid terminal-section replay-layout">
      <article className="card span-5"><div className="section-heading compact"><div><p className="eyebrow">Replay request</p><h2>Historical simulation</h2></div><span>Contract ready · runner unavailable</span></div><div className="form-grid two"><label className="field"><span>Instrument</span><select value={request.instrument} onChange={(event) => setRequest({ ...request, instrument: event.target.value })}><option>NIFTY</option></select></label><label className="field"><span>Date</span><input type="date" value={request.date} onChange={(event) => setRequest({ ...request, date: event.target.value })} /></label><label className="field"><span>Start time</span><input type="time" value={request.startTime} onChange={(event) => setRequest({ ...request, startTime: event.target.value })} /></label><label className="field"><span>End time</span><input type="time" value={request.endTime} onChange={(event) => setRequest({ ...request, endTime: event.target.value })} /></label><label className="field"><span>Strategy</span><select value={request.strategyId} onChange={(event) => setRequest({ ...request, strategyId: event.target.value })}><option value="level-event">Level-event engine</option></select></label><label className="field"><span>Version / config</span><input value={request.strategyVersion} onChange={(event) => setRequest({ ...request, strategyVersion: event.target.value })} /></label><label className="field span-form"><span>Starting capital</span><input type="number" min="1" value={request.startingCapital} onChange={(event) => setRequest({ ...request, startingCapital: Number(event.target.value) })} /></label></div><div className="confirmation-options"><span>Confirmation set</span>{(["volume", "futures", "oi", "options"] as const).map((item) => <label key={item}><input type="checkbox" checked={request.confirmations.includes(item)} onChange={() => toggle(item)} />{item === "oi" ? "OI" : item[0].toUpperCase() + item.slice(1)}</label>)}</div><button className="primary button-wide" disabled><span>Run historical replay</span><Icon name="replay" /></button><p className="availability-note">The form is local only. It never submits or fabricates results while the historical data service is unavailable.</p></article>
      <article className="card span-7"><div className="section-heading compact"><div><p className="eyebrow">Results</p><h2>Backtest output</h2></div></div><BackendUnavailable title="No historical replay API is deployed" description="The Python repository includes a deterministic ReplayRunner that counts classified events and risk approvals without inventing fills or P&L. The web app has no historical snapshot source or authenticated replay endpoint yet." /><div className="terminal-metric-grid two nested"><div className="terminal-metric unavailable"><div className="terminal-metric-head"><span>Trades generated</span></div><strong>Unavailable</strong><small>Awaiting replay result</small></div><div className="terminal-metric unavailable"><div className="terminal-metric-head"><span>Win rate</span></div><strong>Unavailable</strong><small>Requires exit/fill simulation</small></div><div className="terminal-metric unavailable"><div className="terminal-metric-head"><span>P&amp;L</span></div><strong>Unavailable</strong><small>Replay intentionally does not invent fills</small></div><div className="terminal-metric unavailable"><div className="terminal-metric-head"><span>Maximum drawdown</span></div><strong>Unavailable</strong><small>Requires P&amp;L series</small></div></div></article>
    </section>
  </>;
}
