"use client";

import { useEffect, useMemo, useState } from "react";
import { Icon } from "@/components/terminal/Icon";
import { jsonRequest } from "@/lib/controlClient";
import { formatCurrency, formatDateTime, formatDuration, formatNumber } from "@/lib/format";
import type { ControlStatus, ExecutionControl } from "@/lib/terminalTypes";

type ConfigPayload={appSettings:Array<{key:string;category:string;value:unknown;description:string;updated_at:string}>;notifications:{in_app_enabled:boolean;signal_alerts:boolean;risk_blocks:boolean;system_errors:boolean;command_events:boolean;min_confidence:number}|null};
type ExecutionPayload={executionControl:ExecutionControl|null};

export function SettingsPanel({ status, refresh }: { status: ControlStatus; refresh?: () => Promise<void> }) {
  const [apiKey,setApiKey]=useState("");const[apiSecret,setApiSecret]=useState("");const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);
  const[config,setConfig]=useState<ConfigPayload|null>(null);const[settings,setSettings]=useState<Record<string,string>>({});
  const[execution,setExecution]=useState<ExecutionControl|null>(status.executionControl);const[liveCap,setLiveCap]=useState(String(status.executionControl?.max_order_premium??0));const[armText,setArmText]=useState("");
  async function loadConfig(){try{const data=await jsonRequest<ConfigPayload>("/api/control/config");setConfig(data);setSettings(Object.fromEntries(data.appSettings.map((row)=>[row.key,String(row.value)])));}catch(e){setNotice(e instanceof Error?e.message:"Could not load settings");}}
  async function loadExecution(){try{const data=await jsonRequest<ExecutionPayload>("/api/control/execution");setExecution(data.executionControl);setLiveCap(String(data.executionControl?.max_order_premium??0));}catch(e){setNotice(e instanceof Error?e.message:"Could not load execution settings");}}
  useEffect(()=>{void loadConfig();void loadExecution();},[]);
  async function saveCredentials(){setBusy(true);setNotice("");try{await jsonRequest("/api/control/credentials",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apiKey,apiSecret})});setApiKey("");setApiSecret("");setNotice("Groww credentials encrypted and saved. Broker verification was reset until Oracle tests them again.");await refresh?.();}catch(e){setNotice(e instanceof Error?e.message:"Credential save failed");}finally{setBusy(false);}}
  async function saveRuntime(){setBusy(true);setNotice("");try{const numeric=["paper_account_equity","quote_scan_seconds","option_refresh_seconds","feed_poll_seconds","signal_persist_seconds","dashboard_refresh_ms"];const values=Object.fromEntries(Object.entries(settings).map(([key,value])=>[key,numeric.includes(key)?Number(value):value]));await jsonRequest("/api/control/config",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({appSettings:values})});setNotice("Runtime/application settings saved. Market cadence/account sizing take effect on the next engine session start.");await loadConfig();}catch(e){setNotice(e instanceof Error?e.message:"Settings update failed");}finally{setBusy(false);}}
  async function saveNotification(key:string,value:boolean|number){try{await jsonRequest("/api/control/config",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({notifications:{[key]:value}})});await loadConfig();}catch(e){setNotice(e instanceof Error?e.message:"Notification preference failed");}}
  async function executionAction(action:"SET_MODE"|"ARM_LIVE"|"DISARM_LIVE"|"SET_LIMIT",extra:Record<string,unknown>={}){setBusy(true);setNotice("");try{await jsonRequest("/api/control/execution",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...extra})});setArmText("");await loadExecution();await refresh?.();setNotice(action==="ARM_LIVE"?"LIVE execution armed. Starting the trading engine can now place real Groww orders when strategy and risk gates pass.":action==="DISARM_LIVE"?"LIVE execution disarmed. New real orders are blocked.":action==="SET_MODE"?`Execution mode changed to ${String(extra.mode).toUpperCase()}. Live arming was reset.`:"Maximum live order premium saved. Live arming was reset.");}catch(e){setNotice(e instanceof Error?e.message:"Execution setting failed");}finally{setBusy(false);}}
  const map=useMemo(()=>Object.fromEntries((config?.appSettings??[]).map((row)=>[row.key,row])),[config]);
  const mode=execution?.mode??"paper";const armed=Boolean(execution?.live_armed);const engineRunning=Boolean(status.paperEngine.running);
  return <>
    {notice&&<div className="notice" role="status"><Icon name="settings"/>{notice}</div>}
    <section className="dashboard-grid terminal-section">
      <article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Broker access</p><h2>Groww credentials</h2></div><span className={`status-badge ${status.credentials.configured?"good":"warn"}`}>{status.credentials.configured?"Configured":"Not configured"}</span></div><p className="muted">Credentials are encrypted server-side before Supabase storage. Oracle remains the only process that calls Groww.</p><div className="form-grid compact"><label className="field"><span>API key</span><input type="password" autoComplete="off" value={apiKey} onChange={(e)=>setApiKey(e.target.value)} placeholder="Enter current Groww API key"/></label><label className="field"><span>API secret</span><input type="password" autoComplete="off" value={apiSecret} onChange={(e)=>setApiSecret(e.target.value)} placeholder="Enter current Groww API secret"/></label></div><button className="primary" type="button" onClick={()=>void saveCredentials()} disabled={busy||apiKey.length<8||apiSecret.length<8}>Save encrypted credentials</button><div className="diagnostic-list settings-detail"><div><span>Last saved</span><strong>{formatDateTime(status.credentials.updatedAt)}</strong></div><div><span>Oracle auth</span><strong>{status.worker.groww_authenticated?"Verified":"Not verified"}</strong></div><div><span>Market data</span><strong>{status.worker.market_data_status??"Unknown"}</strong></div></div></article>
      <article className={`card span-6 ${mode==="live"?"danger-zone":""}`}><div className="section-heading compact"><div><p className="eyebrow">Execution mode</p><h2>Paper / LIVE broker execution</h2></div><span className={`status-badge ${mode==="live"?(armed?"bad":"warn"):"good"}`}>{mode==="live"?(armed?"LIVE ARMED":"LIVE DISARMED"):"PAPER"}</span></div><p className="muted">Paper remains the default. LIVE sends actual NIFTY option orders from the Oracle static IP only after an explicit arm step.</p><div className="action-grid"><button className={mode==="paper"?"primary":"secondary"} disabled={busy||engineRunning||mode==="paper"} onClick={()=>void executionAction("SET_MODE",{mode:"paper"})}>Paper mode</button><button className={mode==="live"?"danger":"secondary"} disabled={busy||engineRunning||mode==="live"} onClick={()=>void executionAction("SET_MODE",{mode:"live"})}>LIVE mode</button></div><label className="field"><span>Maximum premium per LIVE entry</span><input type="number" min="0" step="100" value={liveCap} onChange={(e)=>setLiveCap(e.target.value)} disabled={engineRunning}/></label><button className="secondary" disabled={busy||engineRunning||Number(liveCap)<0} onClick={()=>void executionAction("SET_LIMIT",{maxOrderPremium:Number(liveCap)})}>Save live premium cap</button>{mode==="live"&&<><div className="notice error"><Icon name="shield"/><div><strong>Real money boundary</strong><p>To arm LIVE execution, type <code>LIVE</code> exactly. A positive premium cap, saved Groww credentials, and a clear kill switch are required.</p></div></div><label className="field"><span>Arm confirmation</span><input value={armText} onChange={(e)=>setArmText(e.target.value)} placeholder="Type LIVE" autoComplete="off" disabled={engineRunning||armed}/></label><div className="action-grid">{armed?<button className="danger" disabled={busy} onClick={()=>void executionAction("DISARM_LIVE")}>Disarm LIVE</button>:<button className="danger" disabled={busy||engineRunning||armText!=="LIVE"||Number(liveCap)<=0} onClick={()=>void executionAction("ARM_LIVE",{confirmation:armText})}>Arm real trading</button>}</div></>}<div className="diagnostic-list settings-detail"><div><span>Product</span><strong>{execution?.product??"MIS"}</strong></div><div><span>Order type</span><strong>{execution?.order_type??"MARKET"}</strong></div><div><span>Live cap</span><strong>{formatCurrency(execution?.max_order_premium)}</strong></div><div><span>Armed at</span><strong>{formatDateTime(execution?.armed_at)}</strong></div></div><p className="availability-note">Mode/cap changes require the trading engine to be stopped. Disarming is always available and blocks new live entries.</p></article>
    </section>
    <section className="dashboard-grid terminal-section">
      <article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Trading runtime</p><h2>Execution &amp; data defaults</h2></div><span>DB-backed</span></div><div className="form-grid compact">
        {["paper_account_equity","quote_scan_seconds","option_refresh_seconds","feed_poll_seconds","signal_persist_seconds","dashboard_refresh_ms"].map((key)=><label className="field" key={key}><span>{map[key]?.description??key.replaceAll("_"," ")}</span><input type="number" min="0" step="any" value={settings[key]??""} onChange={(e)=>setSettings((current)=>({...current,[key]:e.target.value}))}/></label>)}
        <label className="field"><span>{map.default_instrument?.description??"Default instrument"}</span><select value={settings.default_instrument??"NIFTY"} onChange={(e)=>setSettings((current)=>({...current,default_instrument:e.target.value}))}><option>NIFTY</option></select></label><label className="field"><span>{map.timezone?.description??"Timezone"}</span><select value={settings.timezone??"Asia/Kolkata"} onChange={(e)=>setSettings((current)=>({...current,timezone:e.target.value}))}><option value="Asia/Kolkata">Asia/Kolkata (IST)</option></select></label>
      </div><button className="primary" disabled={busy||!config} onClick={()=>void saveRuntime()}>Save runtime settings</button><p className="availability-note">Paper equity is used only for paper sizing. LIVE sizing is bounded by strategy risk, the live premium cap, and Groww's available option-buy margin.</p></article>
      <article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Data &amp; application</p><h2>Current environment</h2></div></div><div className="diagnostic-list"><div><span>Market source</span><strong>Groww via Oracle</strong></div><div><span>Execution</span><strong className={mode==="live"?"bad":"good"}>{mode==="live"?(armed?"LIVE · armed":"LIVE · disarmed"):"PAPER"}</strong></div><div><span>Last quote scan</span><strong>{formatDateTime(status.paperEngine.last_quote_scan)}</strong></div><div><span>Data age</span><strong>{status.paperEngine.data_age_seconds!=null?`${formatNumber(status.paperEngine.data_age_seconds)}s`:"Unavailable"}</strong></div><div><span>Oracle heartbeat</span><strong>{formatDuration(status.worker.last_heartbeat)} ago</strong></div><div><span>Trading timezone</span><strong>{settings.timezone??"Asia/Kolkata"}</strong></div></div></article>
    </section>
    <section className="dashboard-grid terminal-section"><article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Notifications</p><h2>In-app alert preferences</h2></div></div>{config?.notifications?<div className="settings-stack">{([['signal_alerts','Signal alerts'],['risk_blocks','Risk blocks'],['system_errors','System errors'],['command_events','Command events']] as const).map(([key,label])=><label className="toggle-row" key={key}><input type="checkbox" checked={config.notifications?.[key]??false} onChange={(e)=>void saveNotification(key,e.target.checked)}/><span>{label}</span></label>)}<label className="field"><span>Minimum signal confidence</span><input type="number" min="0" max="1" step="0.01" value={config.notifications.min_confidence} onChange={(e)=>void saveNotification("min_confidence",Number(e.target.value))}/></label></div>:<p className="muted">Loading preferences…</p>}<p className="availability-note">Preferences control the persisted terminal alert stream. External email/SMS/push delivery is not configured.</p></article><article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Safety</p><h2>Execution boundaries</h2></div></div><div className="diagnostic-list"><div><span>One-position rule</span><strong>Enabled</strong></div><div><span>Kill switch</span><strong className={status.paperEngine.kill_switch?"bad":"good"}>{status.paperEngine.kill_switch?"ACTIVE":"Clear"}</strong></div><div><span>Static broker egress</span><strong>Oracle only</strong></div><div><span>LIVE entry cap</span><strong>{formatCurrency(execution?.max_order_premium)}</strong></div></div></article></section>
  </>;
}
