"use client";

import { useEffect, useMemo, useState } from "react";
import { Icon } from "@/components/terminal/Icon";
import { jsonRequest } from "@/lib/controlClient";
import { formatDateTime, formatDuration, formatNumber } from "@/lib/format";
import type { ControlStatus } from "@/lib/terminalTypes";

type ConfigPayload={appSettings:Array<{key:string;category:string;value:unknown;description:string;updated_at:string}>;notifications:{in_app_enabled:boolean;signal_alerts:boolean;risk_blocks:boolean;system_errors:boolean;command_events:boolean;min_confidence:number}|null};

export function SettingsPanel({ status }: { status: ControlStatus }) {
  const [apiKey,setApiKey]=useState("");const[apiSecret,setApiSecret]=useState("");const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);
  const[config,setConfig]=useState<ConfigPayload|null>(null);const[settings,setSettings]=useState<Record<string,string>>({});
  async function loadConfig(){try{const data=await jsonRequest<ConfigPayload>("/api/control/config");setConfig(data);setSettings(Object.fromEntries(data.appSettings.map((row)=>[row.key,String(row.value)])));}catch(e){setNotice(e instanceof Error?e.message:"Could not load settings");}}
  useEffect(()=>{void loadConfig();},[]);
  async function saveCredentials(){setBusy(true);setNotice("");try{await jsonRequest("/api/control/credentials",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apiKey,apiSecret})});setApiKey("");setApiSecret("");setNotice("Groww credentials encrypted and saved. Broker verification was reset until Oracle tests them again.");}catch(e){setNotice(e instanceof Error?e.message:"Credential save failed");}finally{setBusy(false);}}
  async function saveRuntime(){setBusy(true);setNotice("");try{const numeric=["paper_account_equity","quote_scan_seconds","option_refresh_seconds","feed_poll_seconds","signal_persist_seconds","dashboard_refresh_ms"];const values=Object.fromEntries(Object.entries(settings).map(([key,value])=>[key,numeric.includes(key)?Number(value):value]));await jsonRequest("/api/control/config",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({appSettings:values})});setNotice("Runtime/application settings saved. Paper runtime settings take effect on the next paper session start.");await loadConfig();}catch(e){setNotice(e instanceof Error?e.message:"Settings update failed");}finally{setBusy(false);}}
  async function saveNotification(key:string,value:boolean|number){try{await jsonRequest("/api/control/config",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({notifications:{[key]:value}})});await loadConfig();}catch(e){setNotice(e instanceof Error?e.message:"Notification preference failed");}}
  const map=useMemo(()=>Object.fromEntries((config?.appSettings??[]).map((row)=>[row.key,row])),[config]);
  return <>
    {notice&&<div className="notice" role="status"><Icon name="settings"/>{notice}</div>}
    <section className="dashboard-grid terminal-section">
      <article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Broker access</p><h2>Groww credentials</h2></div><span className={`status-badge ${status.credentials.configured?"good":"warn"}`}>{status.credentials.configured?"Configured":"Not configured"}</span></div><p className="muted">Credentials are encrypted server-side before Supabase storage. Oracle remains the only process that calls Groww.</p><div className="form-grid compact"><label className="field"><span>API key</span><input type="password" autoComplete="off" value={apiKey} onChange={(e)=>setApiKey(e.target.value)} placeholder="Enter current Groww API key"/></label><label className="field"><span>API secret</span><input type="password" autoComplete="off" value={apiSecret} onChange={(e)=>setApiSecret(e.target.value)} placeholder="Enter current Groww API secret"/></label></div><button className="primary" type="button" onClick={()=>void saveCredentials()} disabled={busy||apiKey.length<8||apiSecret.length<8}>Save encrypted credentials</button><div className="diagnostic-list settings-detail"><div><span>Last saved</span><strong>{formatDateTime(status.credentials.updatedAt)}</strong></div><div><span>Oracle auth</span><strong>{status.worker.groww_authenticated?"Verified":"Not verified"}</strong></div><div><span>Market data</span><strong>{status.worker.market_data_status??"Unknown"}</strong></div></div></article>
      <article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Paper runtime</p><h2>Execution &amp; data defaults</h2></div><span>DB-backed</span></div><div className="form-grid compact">
        {["paper_account_equity","quote_scan_seconds","option_refresh_seconds","feed_poll_seconds","signal_persist_seconds","dashboard_refresh_ms"].map((key)=><label className="field" key={key}><span>{map[key]?.description??key.replaceAll("_"," ")}</span><input type="number" min="0" step="any" value={settings[key]??""} onChange={(e)=>setSettings((current)=>({...current,[key]:e.target.value}))}/></label>)}
        <label className="field"><span>{map.default_instrument?.description??"Default instrument"}</span><select value={settings.default_instrument??"NIFTY"} onChange={(e)=>setSettings((current)=>({...current,default_instrument:e.target.value}))}><option>NIFTY</option></select></label><label className="field"><span>{map.timezone?.description??"Timezone"}</span><select value={settings.timezone??"Asia/Kolkata"} onChange={(e)=>setSettings((current)=>({...current,timezone:e.target.value}))}><option value="Asia/Kolkata">Asia/Kolkata (IST)</option></select></label>
      </div><button className="primary" disabled={busy||!config} onClick={()=>void saveRuntime()}>Save runtime settings</button><p className="availability-note">Market cadence/account equity are loaded when a new paper session starts. Strategy/risk thresholds hot-reload separately from the Strategies/Risk pages.</p></article>
    </section>
    <section className="dashboard-grid terminal-section"><article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Notifications</p><h2>In-app alert preferences</h2></div></div>{config?.notifications?<div className="settings-stack">{([['signal_alerts','Signal alerts'],['risk_blocks','Risk blocks'],['system_errors','System errors'],['command_events','Command events']] as const).map(([key,label])=><label className="toggle-row" key={key}><input type="checkbox" checked={config.notifications?.[key]??false} onChange={(e)=>void saveNotification(key,e.target.checked)}/><span>{label}</span></label>)}<label className="field"><span>Minimum signal confidence</span><input type="number" min="0" max="1" step="0.01" value={config.notifications.min_confidence} onChange={(e)=>void saveNotification("min_confidence",Number(e.target.value))}/></label></div>:<p className="muted">Loading preferences…</p>}<p className="availability-note">Preferences control the persisted terminal alert stream. External email/SMS/push delivery is not configured.</p></article><article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Data &amp; application</p><h2>Current environment</h2></div></div><div className="diagnostic-list"><div><span>Market source</span><strong>Groww via Oracle</strong></div><div><span>Last quote scan</span><strong>{formatDateTime(status.paperEngine.last_quote_scan)}</strong></div><div><span>Data age</span><strong>{status.paperEngine.data_age_seconds!=null?`${formatNumber(status.paperEngine.data_age_seconds)}s`:"Unavailable"}</strong></div><div><span>Oracle heartbeat</span><strong>{formatDuration(status.worker.last_heartbeat)} ago</strong></div><div><span>Theme</span><strong>Terminal dark</strong></div><div><span>Trading timezone</span><strong>{settings.timezone??"Asia/Kolkata"}</strong></div><div><span>Execution</span><strong>Paper only</strong></div></div></article></section>
  </>;
}
