"use client";

import { useEffect, useMemo, useState } from "react";
import { ConfirmDialog } from "@/components/terminal/ConfirmDialog";
import { Icon } from "@/components/terminal/Icon";
import { SignalExplanation } from "@/components/terminal/SignalExplanation";
import StrategyObservability from "@/components/StrategyObservability";
import { jsonRequest } from "@/lib/controlClient";
import { formatCurrency, formatNumber, formatPercent } from "@/lib/format";
import type { ControlCommand, ControlStatus } from "@/lib/terminalTypes";

type Parameter={key:string;category:string;value:number;unit:string;description:string;updated_at:string};
type Preset={id:string;name:string;description:string;parameters:Record<string,number>;is_active:boolean;created_at:string;updated_at:string};
type ConfigPayload={strategyParameters:Parameter[];strategyPresets:Preset[]};

export function StrategiesPanel({ status, refresh }: { status: ControlStatus; refresh: () => Promise<void> }) {
  const [busy,setBusy]=useState("");const[notice,setNotice]=useState("");const[confirmPause,setConfirmPause]=useState(false);const[editing,setEditing]=useState(false);const[config,setConfig]=useState<ConfigPayload|null>(null);const[draft,setDraft]=useState<Record<string,string>>({});const[copyName,setCopyName]=useState("");
  const engine=status.paperEngine;const signal=status.latestSignal?.payload??null;const activeLevel=signal?.level.level_name?status.levels.find((level)=>level.name===signal.level.level_name):undefined;
  const mode=status.executionControl?.mode??engine.mode??"paper";const armed=Boolean(status.executionControl?.live_armed??engine.live_armed);const currentPosition=engine.open_position??engine.open_paper_position;
  async function loadConfig(){try{const data=await jsonRequest<ConfigPayload>("/api/control/config");setConfig(data);setDraft(Object.fromEntries(data.strategyParameters.map((p)=>[p.key,String(p.value)])));}catch(e){setNotice(e instanceof Error?e.message:"Could not load strategy configuration");}}
  useEffect(()=>{void loadConfig();},[]);
  const groups=useMemo(()=>{const map=new Map<string,Parameter[]>();for(const p of config?.strategyParameters??[]){map.set(p.category,[...(map.get(p.category)??[]),p]);}return[...map.entries()];},[config]);
  async function runCommand(command:ControlCommand){setBusy(command);setNotice("");try{const response=await jsonRequest<{duplicate?:boolean}>("/api/control/command",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({command})});setNotice(response.duplicate?"This command is already queued or running.":`${command.replaceAll("_"," ")} queued for Oracle.`);await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Command failed");}finally{setBusy("");setConfirmPause(false);}}
  async function saveParameters(){setBusy("SAVE");setNotice("");try{await jsonRequest("/api/control/config",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({strategyParameters:Object.fromEntries(Object.entries(draft).map(([key,value])=>[key,Number(value)]))})});setNotice("Strategy parameters saved. Oracle hot-reloads them within 30 seconds.");setEditing(false);await loadConfig();}catch(e){setNotice(e instanceof Error?e.message:"Strategy update failed");}finally{setBusy("");}}
  async function duplicate(){setBusy("DUPLICATE");setNotice("");try{const name=copyName.trim()||`NIFTY strategy copy ${new Date().toLocaleDateString("en-CA")}`;await jsonRequest("/api/control/strategies",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"duplicate",name})});setCopyName("");setNotice("Strategy preset duplicated from the current DB thresholds.");await loadConfig();}catch(e){setNotice(e instanceof Error?e.message:"Duplicate failed");}finally{setBusy("");}}
  async function activatePreset(id:string){setBusy("PRESET");setNotice("");try{await jsonRequest("/api/control/strategies",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"activate",id})});setNotice("Preset activated; DB thresholds updated.");await loadConfig();}catch(e){setNotice(e instanceof Error?e.message:"Preset activation failed");}finally{setBusy("");}}
  const liveReady=mode!=="live"||armed;const canStart=Boolean(status.worker.online&&status.credentials.configured&&!engine.running&&!busy&&liveReady);const canStop=Boolean(status.worker.online&&engine.running&&!busy);
  const todaysOrders=status.paperOrders.filter((order)=>order.mode===mode&&new Date(order.created_at).toDateString()===new Date().toDateString());
  const todaysTrades=status.paperTrades.filter((trade)=>(trade.mode??"paper")===mode&&new Date(trade.executed_at).toDateString()===new Date().toDateString());
  return <>
    {notice&&<div className="notice" role="status"><Icon name="activity"/>{notice}</div>}
    <section className={`terminal-section strategy-card card ${mode==="live"&&armed?"danger-zone":""}`}><div className="strategy-header"><div className="title-with-icon"><div className="card-icon"><Icon name="strategy"/></div><div><p className="eyebrow">Level-event strategy</p><h2>NIFTY participation + futures confirmation</h2><p className="muted">Cash breadth · heavyweight confirmation · futures/OI · options activity · synthetic VWAP · {mode==="live"?"Groww execution":"paper execution"}</p></div></div><div className="strategy-mode-stack"><span className={`status-badge ${engine.running?"good":"warn"}`}><span className={`status-dot ${engine.running?"good":"warn"}`}/>{engine.running?"Active":"Paused"}</span><span className={`mode-badge ${mode==="live"?"live":""}`}><span className={`status-dot ${mode==="live"?(armed?"bad":"warn"):"amber"}`}/>{mode==="live"?(armed?"LIVE · ARMED":"LIVE · DISARMED"):"PAPER"}</span></div></div>
      {mode==="live"&&!armed&&<div className="notice error"><Icon name="shield"/><div><strong>LIVE mode is not armed</strong><p>Go to Settings, set a live premium cap, type LIVE, and arm real execution before starting the engine.</p></div></div>}
      <div className="strategy-stats"><div><span>Instrument</span><strong>NIFTY</strong></div><div><span>Current signal</span><strong>{signal?`${signal.event} · ${signal.direction}`.toUpperCase():"Unavailable"}</strong></div><div><span>Trades today</span><strong>{todaysOrders.length}</strong></div><div><span>Daily P&amp;L</span><strong>{todaysTrades.some((trade)=>trade.pnl!==null)?formatCurrency(todaysTrades.reduce((sum,trade)=>sum+(trade.pnl??0),0)):"Unavailable"}</strong></div><div><span>Confidence</span><strong>{signal?formatPercent(signal.confidence):"Unavailable"}</strong></div><div><span>Position</span><strong>{currentPosition?.trading_symbol??"None"}</strong></div></div>
      <div className="strategy-actions"><button className={mode==="live"?"danger":"primary"} type="button" onClick={()=>void runCommand("START_ENGINE")} disabled={!canStart}>{busy==="START_ENGINE"?<Icon name="refresh" className="spin"/>:<Icon name="activity"/>}{mode==="live"?"Start LIVE engine":"Activate / resume"}</button><button className="secondary" type="button" onClick={()=>setConfirmPause(true)} disabled={!canStop}><Icon name="stop"/>Pause</button><button className="secondary" onClick={()=>void runCommand("STOP_ENGINE")} disabled={!canStop}>Deactivate</button><button className="secondary" onClick={()=>setEditing((v)=>!v)} disabled={!config}>{editing?"Close editor":"Edit"}</button><button className="secondary" onClick={()=>void duplicate()} disabled={Boolean(busy)}>Duplicate</button><span className={`mode-action selected ${mode==="live"?"live":""}`}><span className={`status-dot ${mode==="live"?(armed?"bad":"warn"):"amber"}`}/>{mode==="live"?"LIVE mode":"Paper mode"}</span></div><p className="availability-note">The strategy logic is shared across modes. PAPER writes simulated fills; armed LIVE sends actual NSE F&amp;O option orders through Groww from Oracle.</p>
    </section>
    {editing&&<section className="terminal-section card"><div className="section-heading compact"><div><p className="eyebrow">Configuration</p><h2>Edit all strategy thresholds</h2></div><button className="primary" disabled={busy==="SAVE"} onClick={()=>void saveParameters()}>Save all</button></div>{groups.map(([category,parameters])=><div key={category} className="settings-stack"><h3>{category.replaceAll("_"," ")}</h3><div className="form-grid compact">{parameters.map((p)=><label className="field" key={p.key}><span>{p.description} {p.unit&&`· ${p.unit}`}</span><input type="number" step="any" value={draft[p.key]??""} onChange={(e)=>setDraft((current)=>({...current,[p.key]:e.target.value}))}/><small>{p.key}</small></label>)}</div></div>)}</section>}
    <section className="dashboard-grid terminal-section"><article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Presets</p><h2>Strategy versions</h2></div></div><div className="diagnostic-list">{(config?.strategyPresets??[]).map((preset)=><div key={preset.id}><span>{preset.name}{preset.is_active?" · active":""}</span><button className="secondary compact" disabled={preset.is_active||Boolean(busy)} onClick={()=>void activatePreset(preset.id)}>{preset.is_active?"Active":"Activate"}</button></div>)}</div><div className="inline-form"><input value={copyName} onChange={(e)=>setCopyName(e.target.value)} placeholder="Optional copy name"/><button className="secondary" disabled={Boolean(busy)} onClick={()=>void duplicate()}>Duplicate current</button></div></article><article className="card span-6"><div className="section-heading compact"><div><p className="eyebrow">Runtime</p><h2>Strategy health</h2></div></div><div className="diagnostic-list"><div><span>Engine state</span><strong>{engine.state??"Unavailable"}</strong></div><div><span>Execution</span><strong className={mode==="live"?"bad":"good"}>{mode==="live"?(armed?"LIVE ARMED":"LIVE DISARMED"):"PAPER"}</strong></div><div><span>Feed</span><strong className={engine.feed_connected?"good":"warn"}>{engine.feed_connected?"Connected":"Waiting"}</strong></div><div><span>Constituent coverage</span><strong>{engine.constituents_fresh??0} / {engine.constituents_total??50}</strong></div><div><span>Kill switch</span><strong className={engine.kill_switch?"bad":"good"}>{engine.kill_switch?"Active":"Clear"}</strong></div><div><span>Latest risk verdict</span><strong>{signal?(signal.risk.allowed?"Allow":"Block"):"Unavailable"}</strong></div><div><span>Selected premium</span><strong>{signal?.contract.contract?formatNumber(signal.contract.contract.ltp):"Unavailable"}</strong></div></div></article></section>
    <section className="dashboard-grid terminal-section"><article className="card span-7"><div className="section-heading compact"><div><p className="eyebrow">Explainability</p><h2>Latest signal reasoning</h2></div><span>{status.latestSignal?new Date(status.latestSignal.observed_at).toLocaleString("en-IN"):"No observation"}</span></div><SignalExplanation signal={signal} level={activeLevel}/></article><article className="card span-5"><div className="section-heading compact"><div><p className="eyebrow">Quick weights</p><h2>Direction mix</h2></div></div><div className="diagnostic-list">{["combined_cash_weight","combined_futures_weight","combined_options_weight","combined_vwap_weight"].map((key)=><div key={key}><span>{key.replace("combined_","").replace("_weight","")}</span><strong>{config?.strategyParameters.find((p)=>p.key===key)?formatPercent(config.strategyParameters.find((p)=>p.key===key)!.value):"—"}</strong></div>)}</div></article></section>
    <section className="terminal-section research-section"><div className="section-heading compact"><div><p className="eyebrow">Research telemetry</p><h2>Full strategy observability</h2></div><span>DB thresholds · 50-stock volume · dynamic exits</span></div><StrategyObservability embedded/></section>
    <ConfirmDialog open={confirmPause} title={`Pause the ${mode.toUpperCase()} strategy?`} description={mode==="live"?"This stops the trading engine. If a LIVE position is open, pause does not itself close it; use Close position or the kill switch before stopping protection.":"This stops paper strategy processing through Oracle until resumed."} confirmLabel={`Pause ${mode} engine`} busy={busy==="STOP_ENGINE"} onCancel={()=>setConfirmPause(false)} onConfirm={()=>void runCommand("STOP_ENGINE")}/>
  </>;
}
