"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ConfirmDialog } from "@/components/terminal/ConfirmDialog";
import { EmptyState } from "@/components/terminal/EmptyState";
import { BrandMark, Icon } from "@/components/terminal/Icon";
import { MetricCard } from "@/components/terminal/MetricCard";
import { PerformanceChart } from "@/components/terminal/PerformanceChart";
import { SignalExplanation } from "@/components/terminal/SignalExplanation";
import { TerminalShell } from "@/components/terminal/TerminalShell";
import { jsonRequest } from "@/lib/controlClient";
import { formatCurrency, formatDateTime, formatNumber, formatPercent } from "@/lib/format";
import { calculatePaperAnalytics } from "@/lib/terminalAnalytics";
import type { ControlCommand, ControlStatus, TradingDataSnapshot } from "@/lib/terminalTypes";

type Confirmation =
  | { kind: "command"; command: "STOP_ENGINE" | "STOP" | "EXIT_PAPER_POSITION" | "KILL_SWITCH" }
  | { kind: "level"; id: string; name: string }
  | null;

function normalizeStatus(data: ControlStatus, current?: ControlStatus | null): ControlStatus {
  return { ...data, recentSignals: data.recentSignals ?? current?.recentSignals ?? [], paperOrders: data.paperOrders ?? current?.paperOrders ?? [], paperTrades: data.paperTrades ?? current?.paperTrades ?? [], paperOutcomes: data.paperOutcomes ?? current?.paperOutcomes ?? [] };
}

export default function SignalDashboard() {
  const [auth,setAuth]=useState<"checking"|"guest"|"ready">("checking");const[password,setPassword]=useState("");const[status,setStatus]=useState<ControlStatus|null>(null);const[apiKey,setApiKey]=useState("");const[apiSecret,setApiSecret]=useState("");const[levelName,setLevelName]=useState("");const[levelKind,setLevelKind]=useState<"support"|"resistance">("support");const[levelPrice,setLevelPrice]=useState("");const[busy,setBusy]=useState("");const[notice,setNotice]=useState("");const[confirmation,setConfirmation]=useState<Confirmation>(null);const[pollMs,setPollMs]=useState(3000);
  const loadTradingData=useCallback(async()=>{try{const data=await jsonRequest<TradingDataSnapshot>("/api/control/trading");setStatus((current)=>current?{...current,...data}:current);}catch(reason){const message=reason instanceof Error?reason.message:"Failed to load trading history";if(message==="unauthorized")setAuth("guest");else setNotice((current)=>current||`Trading history: ${message}`);}},[]);
  const loadStatus=useCallback(async()=>{try{const data=await jsonRequest<ControlStatus>("/api/control/status");setStatus((current)=>normalizeStatus(data,current));setAuth("ready");}catch(reason){const message=reason instanceof Error?reason.message:"Failed to load dashboard status";if(message==="unauthorized")setAuth("guest");else{setNotice(message);setAuth("ready");}}},[]);
  useEffect(()=>{void jsonRequest<{authenticated:boolean}>("/api/auth/status").then((data)=>data.authenticated?loadStatus():setAuth("guest")).catch(()=>setAuth("guest"));},[loadStatus]);
  useEffect(()=>{if(auth!=="ready")return;void jsonRequest<{appSettings?:Array<{key:string;value:unknown}>}>("/api/control/config").then((data)=>{const parsed=Number(data.appSettings?.find((row)=>row.key==="dashboard_refresh_ms")?.value);if(Number.isFinite(parsed))setPollMs(Math.min(Math.max(parsed,1000),60000));}).catch(()=>undefined);},[auth]);
  useEffect(()=>{if(auth!=="ready")return;const timer=window.setInterval(()=>void loadStatus(),pollMs);return()=>window.clearInterval(timer);},[auth,loadStatus,pollMs]);
  useEffect(()=>{if(auth!=="ready")return;void loadTradingData();const timer=window.setInterval(()=>void loadTradingData(),15000);return()=>window.clearInterval(timer);},[auth,loadTradingData]);
  async function login(event:FormEvent){event.preventDefault();setBusy("login");setNotice("");try{await jsonRequest("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});setPassword("");await loadStatus();}catch(reason){setNotice(reason instanceof Error?reason.message:"Login failed");}finally{setBusy("");}}
  async function saveCredentials(event:FormEvent){event.preventDefault();setBusy("credentials");setNotice("");try{await jsonRequest("/api/control/credentials",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apiKey,apiSecret})});setApiKey("");setApiSecret("");setNotice("Groww credentials encrypted and saved. Re-run authentication before trusting broker status.");await loadStatus();}catch(reason){setNotice(reason instanceof Error?reason.message:"Could not save credentials");}finally{setBusy("");}}
  async function saveLevel(event:FormEvent){event.preventDefault();setBusy("level");setNotice("");try{await jsonRequest("/api/control/levels",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:levelName,kind:levelKind,price:Number(levelPrice)})});setLevelName("");setLevelPrice("");setNotice("Support/resistance level saved.");await loadStatus();}catch(reason){setNotice(reason instanceof Error?reason.message:"Could not save level");}finally{setBusy("");}}
  async function removeLevel(id:string){setBusy(`delete-${id}`);setNotice("");try{await jsonRequest("/api/control/levels",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});setNotice("Trading level removed.");await loadStatus();}catch(reason){setNotice(reason instanceof Error?reason.message:"Could not remove level");}finally{setBusy("");setConfirmation(null);}}
  async function command(commandName:ControlCommand,payload:Record<string,unknown>={}){setBusy(commandName);setNotice("");try{const result=await jsonRequest<{duplicate?:boolean}>("/api/control/command",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({command:commandName,payload})});setNotice(result.duplicate?`${commandName.replaceAll("_"," ")} is already queued or running.`:`${commandName.replaceAll("_"," ")} queued for the Oracle worker.`);await loadStatus();}catch(reason){setNotice(reason instanceof Error?reason.message:"Command failed");}finally{setBusy("");setConfirmation(null);}}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});setStatus(null);setAuth("guest");}
  if(auth==="checking")return <main className="center-shell"><div className="loading-panel" role="status" aria-live="polite"><BrandMark large/><div><p className="eyebrow">Growing Trader</p><h1>Opening your terminal</h1><p className="muted">Checking the secure dashboard session…</p></div><div className="loading-track" aria-hidden="true"><span/></div></div></main>;
  if(auth==="guest")return <main className="center-shell"><section className="login-shell"><div className="login-context"><div className="brand-lockup"><BrandMark/><span>Growing Trader</span></div><div className="login-copy"><p className="eyebrow">Private operations workspace</p><h1>Read the market.<br/><span>Control the risk.</span></h1><p>A secure terminal for NIFTY research with selectable paper or explicitly armed LIVE execution.</p></div><div className="login-network" aria-label="System architecture"><span><Icon name="layers"/>Vercel</span><i/><span><Icon name="database"/>Supabase</span><i/><span><Icon name="server"/>Oracle</span></div><p className="paper-note"><span className="status-dot amber"/> PAPER is the default</p></div><form className="login-card" onSubmit={login}><div className="login-card-icon"><Icon name="lock"/></div><p className="eyebrow">Secure access</p><h2>Welcome back</h2><p className="muted">Enter your dashboard password to continue.</p><label className="field login-field"><span>Dashboard password</span><div className="input-wrap"><Icon name="key"/><input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="current-password" placeholder="Enter your password" required autoFocus/></div></label><button className="primary button-wide" disabled={busy==="login"}>{busy==="login"?<><Icon name="refresh" className="spin"/>Signing in…</>:<>Open terminal<Icon name="arrow-right"/></>}</button>{notice&&<p className="notice error" role="alert">{notice}</p>}<div className="security-note"><Icon name="shield"/><span>Credentials stay encrypted and are never returned to this browser.</span></div></form></section></main>;

  const worker=status?.worker??{};const engine=status?.paperEngine??{running:false,state:"stopped"};const mode=status?.executionControl?.mode??engine.mode??"paper";const liveArmed=Boolean(status?.executionControl?.live_armed??engine.live_armed);const activePosition=engine.open_position??engine.open_paper_position;const signal=status?.latestSignal?.payload??null;const modeOrders=(status?.paperOrders??[]).filter((order)=>order.mode===mode);const modeTrades=(status?.paperTrades??[]).filter((trade)=>(trade.mode??"paper")===mode);const analytics=calculatePaperAnalytics(modeTrades,modeOrders);const backendErrors=status?.controlPlane.errors??{};const currentExposure=engine.current_exposure??(activePosition?.entry_price&&activePosition.quantity?activePosition.entry_price*activePosition.quantity:null);const activeLevel=signal?.level.level_name?status?.levels.find((level)=>level.name===signal.level.level_name):undefined;const oracleState=worker.state==="stopped"?"STOPPED":worker.online?"ONLINE":worker.stale?"STALE":"OFFLINE";const oracleTone=worker.online?"good":worker.stale?"warn":"bad";const engineTone=engine.state==="error"?"bad":engine.running?"good":"warn";const canBrokerTest=Boolean(worker.online&&status?.credentials.configured&&!busy);const liveReady=mode!=="live"||liveArmed;const canStartEngine=Boolean(worker.online&&status?.credentials.configured&&!engine.running&&!busy&&liveReady);const canStopEngine=Boolean(worker.online&&engine.running&&!busy);const hasPosition=Boolean(activePosition);const killActive=Boolean(engine.kill_switch);const modeLabel=mode==="live"?(liveArmed?"LIVE · ARMED":"LIVE · DISARMED"):"PAPER";
  const confirmationCopy=confirmation?.kind==="level"?{title:`Remove ${confirmation.name}?`,description:"This deletes the persisted strategy level. The signal engine will no longer receive it on subsequent reads.",label:"Remove level",busy:busy===`delete-${confirmation.id}`}:
    confirmation?.command==="STOP"?{title:"Stop the Oracle control agent?",description:"The worker will stop polling commands and updating market status until it is restarted outside the web application.",label:"Stop Oracle",busy:busy==="STOP"}:
    confirmation?.command==="EXIT_PAPER_POSITION"?{title:`Close the open ${mode.toUpperCase()} position?`,description:mode==="live"?"Oracle will submit a real Groww market SELL for the current LIVE option quantity.":"Oracle will close the current paper position at the next observed option-chain LTP.",label:mode==="live"?"SELL / close LIVE position":"Close paper position",busy:busy==="EXIT_PAPER_POSITION"}:
    confirmation?.command==="KILL_SWITCH"?{title:`Activate the ${mode.toUpperCase()} kill switch?`,description:mode==="live"?"New entries are blocked and Oracle will attempt a real Groww SELL for the open LIVE position when close-on-kill is enabled.":"New entries are blocked and Oracle will close the open paper position at the next observable option mark.",label:"Activate kill switch",busy:busy==="KILL_SWITCH"}:
    {title:`Pause the ${mode.toUpperCase()} engine?`,description:mode==="live"?"This stops strategy processing. If a LIVE position is open, close it or use the kill switch before stopping app-managed protection.":"This stops paper strategy processing through the existing command queue.",label:`Pause ${mode} engine`,busy:busy==="STOP_ENGINE"};
  const noticeIsError=/required|failed|could not|offline|unauthorized|error/i.test(notice);
  return <TerminalShell activeRoute="dashboard" status={status} onLogout={logout}>
    <section className="page-hero terminal-page-hero"><div><p className="eyebrow">Command center · {modeLabel}</p><h1>Trading operations</h1><p className="muted">A real-data view across market state, strategy execution, risk decisions, orders, and diagnostics.</p></div><div className="hero-actions"><span className={`mode-badge ${mode==="live"?"live":""}`}><span className={`status-dot ${mode==="live"?(liveArmed?"bad":"warn"):"amber"}`}/>{modeLabel}</span><Link className="ghost" href="/settings"><Icon name="settings"/>Execution mode</Link><div className="hero-health"><span className={`status-dot ${status?.controlPlane.healthy?"good":"bad"}`}/><div><small>Control plane</small><strong>{status?.controlPlane.healthy?"Healthy":"Degraded"}</strong></div></div></div></section>
    {mode==="live"&&liveArmed&&<div className="notice error" role="status"><Icon name="shield"/><div><strong>LIVE broker execution armed</strong><p>Eligible entries and exits can place real Groww F&amp;O orders from Oracle.</p></div></div>}
    {notice&&<div className={`notice${noticeIsError?" error":""}`} role={noticeIsError?"alert":"status"} aria-live="polite"><Icon name={noticeIsError?"shield":"activity"}/><span>{notice}</span></div>}{Object.keys(backendErrors).length>0&&<div className="notice error" role="alert"><Icon name="shield"/><div><strong>Control plane degraded</strong><pre className="error-box">{JSON.stringify(backendErrors,null,2)}</pre></div></div>}
    <section className="terminal-metric-grid five dashboard-kpis" aria-label="Trading performance metrics"><MetricCard label="Today's P&L" value={formatCurrency(analytics.todayPnl)} detail={`${analytics.tradesToday} ${mode} orders today`} tone={(analytics.todayPnl??0)>=0?"positive":"negative"} unavailable={analytics.todayPnl===null}/><MetricCard label="Capital deployed" value={formatCurrency(currentExposure)} detail={`Open ${mode} premium`} unavailable={currentExposure===null}/><MetricCard label="Current exposure" value={formatCurrency(currentExposure)} detail={`${mode.toUpperCase()} premium exposure`} icon="shield" unavailable={currentExposure===null}/><MetricCard label="Active positions" value={hasPosition?"1":"0"} detail="One-position rule" icon="positions"/><MetricCard label="Active strategies" value={engine.running?"1":"0"} detail={engine.state??"Unknown state"} icon="strategy"/><MetricCard label="Weekly P&L" value={formatCurrency(analytics.weekPnl)} unavailable={analytics.weekPnl===null}/><MetricCard label="Monthly P&L" value={formatCurrency(analytics.monthPnl)} unavailable={analytics.monthPnl===null}/><MetricCard label="Realized P&L" value={formatCurrency(analytics.totalPnl)} unavailable={analytics.totalPnl===null}/><MetricCard label="Unrealized P&L" value={formatCurrency(activePosition?.unrealized_pnl)} unavailable={activePosition?.unrealized_pnl==null} tone={(activePosition?.unrealized_pnl??0)>=0?"positive":"negative"}/><MetricCard label="Available capital" value={formatCurrency(engine.available_capital)} unavailable={engine.available_capital==null}/><MetricCard label="Win rate" value={formatPercent(analytics.winRate)} unavailable={analytics.winRate===null}/><MetricCard label="Largest winner" value={formatCurrency(analytics.largestWinner)} tone="positive" unavailable={analytics.largestWinner===null}/><MetricCard label="Largest loser" value={formatCurrency(analytics.largestLoser)} tone="negative" unavailable={analytics.largestLoser===null}/><MetricCard label="Market status" value={(engine.state??worker.market_data_status??"Unavailable").replaceAll("_"," ").toUpperCase()} detail={engine.feed_connected?"Feed connected":"Feed disconnected"} icon="wifi"/><MetricCard label="Trades today" value={String(analytics.tradesToday)} detail={`Persisted ${mode} orders`} icon="orders"/></section>
    <section className="command-bar terminal-section" aria-label="Strategy controls"><div><p className="eyebrow">Execution controls</p><h2>Strategy safety</h2><p>{mode==="live"?"LIVE actions route real broker execution through Oracle.":"PAPER actions use simulated fills only."}</p></div><div className="command-actions"><button className="secondary" type="button" onClick={()=>setConfirmation({kind:"command",command:"STOP_ENGINE"})} disabled={!canStopEngine}><Icon name="stop"/>Pause all</button><button className={mode==="live"?"danger":"primary"} type="button" onClick={()=>void command("START_ENGINE")} disabled={!canStartEngine}>{busy==="START_ENGINE"?<Icon name="refresh" className="spin"/>:<Icon name="activity"/>}{mode==="live"?"Start LIVE":"Resume strategies"}</button><button className="danger" type="button" disabled={!worker.online||!hasPosition||Boolean(busy)} onClick={()=>setConfirmation({kind:"command",command:"EXIT_PAPER_POSITION"})}>{mode==="live"?"SELL / close position":"Close all positions"}</button>{killActive?<button className="secondary" type="button" disabled={!worker.online||Boolean(busy)} onClick={()=>void command("RESET_KILL_SWITCH")}>Reset kill switch</button>:<button className="kill-switch compact" type="button" disabled={!worker.online||Boolean(busy)} onClick={()=>setConfirmation({kind:"command",command:"KILL_SWITCH"})}><Icon name="shield"/><span><strong>KILL SWITCH</strong><small>{mode==="live"?"Block + broker exit":"Block + close paper"}</small></span></button>}</div></section>
    <section className="dashboard-grid terminal-section"><article className="card span-8"><PerformanceChart trades={modeTrades}/></article><article className="card span-4"><div className="section-heading compact"><div><p className="eyebrow">Market state</p><h2>NIFTY feed</h2></div><span className={`status-badge ${engineTone}`}><span className={`status-dot ${engineTone}`}/>{engine.state??"Unknown"}</span></div><div className="market-state-grid"><div><span>NIFTY spot</span><strong>{formatNumber(engine.nifty_ltp)}</strong></div><div><span>NIFTY future</span><strong>{formatNumber(engine.future_ltp)}</strong><small>{engine.future_symbol??"Unavailable"}</small></div><div><span>Fresh constituents</span><strong>{engine.constituents_fresh??0} / {engine.constituents_total??50}</strong></div><div><span>Data age</span><strong>{typeof engine.data_age_seconds==="number"?`${engine.data_age_seconds.toFixed(1)}s`:"Unavailable"}</strong></div></div><Link className="inline-link" href="/market">Open market overview <Icon name="arrow-right"/></Link></article></section>
    <section className="dashboard-grid terminal-section"><article className="card span-7"><div className="section-heading compact"><div><p className="eyebrow">Latest signal</p><h2>Engine reasoning</h2></div><span>{status?.latestSignal?formatDateTime(status.latestSignal.observed_at):"No observation"}</span></div><SignalExplanation signal={signal} level={activeLevel}/></article><article className="card span-5"><div className="section-heading compact"><div><p className="eyebrow">System status</p><h2>Runtime services</h2></div></div><div className="runtime-list"><div><span className={`status-icon ${oracleTone}`}><Icon name="server"/></span><div><strong>Oracle agent</strong><small>Heartbeat {formatDateTime(worker.last_heartbeat)}</small></div><span className={`status-badge ${oracleTone}`}><span className={`status-dot ${oracleTone}`}/>{oracleState}</span></div><div><span className={`status-icon ${worker.groww_authenticated?"good":"warn"}`}><Icon name="shield"/></span><div><strong>Groww authentication</strong><small>{status?.credentials.configured?"Encrypted credentials saved":"Credentials missing"}</small></div><span className={`status-badge ${worker.groww_authenticated?"good":"warn"}`}>{worker.groww_authenticated?"Verified":"Pending"}</span></div><div><span className={`status-icon ${engineTone}`}><Icon name="strategy"/></span><div><strong>{mode.toUpperCase()} trading engine</strong><small>{engine.feed_connected?"Market feed connected":"Market feed disconnected"}</small></div><span className={`status-badge ${engineTone}`}>{(engine.state??"Unknown").replaceAll("_"," ")}</span></div><div><span className={`status-icon ${killActive?"bad":"good"}`}><Icon name="shield"/></span><div><strong>Risk gate</strong><small>{killActive?"New entries blocked":"Normal risk engine"}</small></div><span className={`status-badge ${killActive?"bad":"good"}`}>{killActive?"KILL":"CLEAR"}</span></div></div></article></section>
    <section className="dashboard-grid terminal-section"><article className="card span-7"><div className="section-heading compact"><div><p className="eyebrow">Open inventory</p><h2>Current position</h2></div><Link href="/positions" className="inline-link">All positions <Icon name="arrow-right"/></Link></div>{!activePosition?<EmptyState icon="positions" title={`No open ${mode.toUpperCase()} position`} description="A position appears only after a persisted signal passes risk checks and execution succeeds."/>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Instrument</th><th>Qty</th><th>Entry</th><th>LTP</th><th>Unrealized P&amp;L</th><th>Opened</th></tr></thead><tbody><tr><td><strong>{activePosition.trading_symbol}</strong></td><td className="numeric">{formatNumber(activePosition.quantity,0)}</td><td className="numeric">{formatNumber(activePosition.entry_price)}</td><td className="numeric">{formatNumber(activePosition.current_price)}</td><td className={`numeric ${(activePosition.unrealized_pnl??0)>=0?"good":"bad"}`}>{formatCurrency(activePosition.unrealized_pnl)}</td><td>{formatDateTime(activePosition.opened_at)}</td></tr></tbody></table></div>}</article><article className="card span-5"><div className="section-heading compact"><div><p className="eyebrow">Recent orders</p><h2>{mode.toUpperCase()} lifecycle</h2></div><Link href="/orders" className="inline-link">All orders <Icon name="arrow-right"/></Link></div>{!modeOrders.length?<EmptyState compact icon="orders" title={`No ${mode} orders`} description="No order records are persisted yet for this execution mode."/>:<div className="compact-order-list">{modeOrders.slice(0,5).map((order)=><div key={order.id}><span className={`side-badge ${order.side.toLowerCase()}`}>{order.side}</span><div><strong>{order.trading_symbol}</strong><small>{formatDateTime(order.created_at)}</small></div><div><strong>{formatNumber(order.quantity,0)}</strong><small>{order.status}</small></div></div>)}</div>}</article></section>
    <section className="dashboard-grid terminal-section"><article className="card span-7"><div className="section-heading compact"><div><p className="eyebrow">Broker &amp; Oracle</p><h2>Secure connectivity</h2></div><span className="secure-badge"><Icon name="lock"/>Server-side encrypted</span></div><form className="credential-form" onSubmit={saveCredentials}><label className="field"><span>Groww API key</span><input type="password" value={apiKey} onChange={(e)=>setApiKey(e.target.value)} autoComplete="off" placeholder="Never returned after save" required/></label><label className="field"><span>Groww API secret</span><input type="password" value={apiSecret} onChange={(e)=>setApiSecret(e.target.value)} autoComplete="off" placeholder="Never returned after save" required/></label><button className="primary" disabled={busy==="credentials"}>{busy==="credentials"?<Icon name="refresh" className="spin"/>:<Icon name="lock"/>}Save credentials</button></form><div className="broker-actions"><button className="secondary" type="button" onClick={()=>void command("TEST_AUTH")} disabled={!canBrokerTest}>Test authentication</button><button className="secondary" type="button" onClick={()=>void command("TEST_MARKET_DATA")} disabled={!canBrokerTest}>Test market data</button><Link className="secondary" href="/settings">Paper / LIVE settings</Link><button className="danger" type="button" onClick={()=>setConfirmation({kind:"command",command:"STOP"})} disabled={!worker.online||Boolean(busy)}>Stop Oracle</button></div></article><article className="card span-5"><div className="section-heading compact"><div><p className="eyebrow">Latest command</p><h2>{status?.latestCommand?.command?.replaceAll("_"," ")??"No command"}</h2></div><span className="status-badge neutral">{status?.latestCommand?.status??"Unavailable"}</span></div><div className="diagnostic-list"><div><span>Created</span><strong>{formatDateTime(status?.latestCommand?.created_at)}</strong></div><div><span>Completed</span><strong>{formatDateTime(status?.latestCommand?.completed_at)}</strong></div></div>{status?.latestCommand?.error&&<pre className="error-box">{status.latestCommand.error}</pre>}{status?.latestCommand?.result&&<pre className="json-box">{JSON.stringify(status.latestCommand.result,null,2)}</pre>}</article></section>
    <section className="terminal-section card"><div className="section-heading compact"><div><p className="eyebrow">Strategy inputs</p><h2>Support &amp; resistance levels</h2></div><span>{status?.levels.length??0} persisted levels</span></div><form className="level-form" onSubmit={saveLevel}><label className="field"><span>Name</span><input value={levelName} onChange={(e)=>setLevelName(e.target.value)} placeholder="S1 / R1" required/></label><label className="field"><span>Type</span><select value={levelKind} onChange={(e)=>setLevelKind(e.target.value as "support"|"resistance")}><option value="support">Support</option><option value="resistance">Resistance</option></select></label><label className="field"><span>Price</span><input type="number" inputMode="decimal" step="0.05" min="0" value={levelPrice} onChange={(e)=>setLevelPrice(e.target.value)} placeholder="25,000" required/></label><button className="primary add-button" disabled={busy==="level"}>{busy==="level"?<Icon name="refresh" className="spin"/>:<Icon name="plus"/>}{busy==="level"?"Saving…":"Add level"}</button></form>{!status?.levels.length?<EmptyState compact icon="layers" title="No levels configured" description="Add the first support or resistance level above."/>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Name</th><th>Type</th><th>Price</th><th>Source</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{status.levels.map((level)=><tr key={level.id}><td><strong>{level.name}</strong></td><td><span className={`level-kind ${level.kind}`}>{level.kind}</span></td><td className="numeric">{formatNumber(Number(level.price))}</td><td>{level.source}</td><td><span className={`status-badge ${level.enabled?"good":"neutral"}`}><span className={`status-dot ${level.enabled?"good":"neutral"}`}/>{level.enabled?"Enabled":"Disabled"}</span></td><td><button type="button" className="mini-danger" onClick={()=>setConfirmation({kind:"level",id:level.id,name:level.name})} disabled={busy===`delete-${level.id}`} aria-label={`Remove ${level.name}`}><Icon name="trash"/></button></td></tr>)}</tbody></table></div>}</section>
    <section className="terminal-section card"><div className="section-heading compact"><div><p className="eyebrow">Emergency control</p><h2>{mode.toUpperCase()} kill behavior</h2></div><Link href="/risk" className="inline-link">Risk management <Icon name="arrow-right"/></Link></div><div className="diagnostic-list"><div><span>Kill switch</span><strong className={killActive?"bad":"good"}>{killActive?"ACTIVE":"Clear"}</strong></div><div><span>New entries</span><strong>{killActive?"Blocked":"Normal risk policy"}</strong></div><div><span>Open position</span><strong>{activePosition?.trading_symbol??"None"}</strong></div><div><span>Broker execution</span><strong className={mode==="live"?(liveArmed?"bad":"warn"):"good"}>{mode==="live"?(liveArmed?"LIVE ARMED":"LIVE DISARMED"):"Disabled in PAPER"}</strong></div></div></section>
    <footer className="dashboard-footer"><span><span className="status-dot good"/>Authenticated control plane</span><span>{modeLabel} · Refresh {Math.round(pollMs/1000)}s</span></footer>
    <ConfirmDialog open={confirmation!==null} title={confirmationCopy.title} description={confirmationCopy.description} confirmLabel={confirmationCopy.label} busy={confirmationCopy.busy} onCancel={()=>setConfirmation(null)} onConfirm={()=>{if(confirmation?.kind==="level")void removeLevel(confirmation.id);else if(confirmation?.command==="EXIT_PAPER_POSITION")void command("EXIT_PAPER_POSITION",{fraction:1});else if(confirmation?.command==="KILL_SWITCH")void command("KILL_SWITCH",{close_position:true,reason:"Activated from dashboard"});else if(confirmation)void command(confirmation.command);}}/>
  </TerminalShell>;
}
